/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTAS;

import CONTROLADOR.ctrlRegistroNuevoProfe;
import MODELO.Profesor;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yordan
 */
public class frmCreateNewProfe extends javax.swing.JFrame {

    /**
     * Creates new form frmCreateNewProfe
     */
    private ctrlRegistroNuevoProfe controlador;

    public frmCreateNewProfe() {
        initComponents();
        controlador = new ctrlRegistroNuevoProfe(); // Inicializar la instancia de la clase controladora
        controlador.cargarDatosProfesores((DefaultTableModel) JTableProfesoresExistentes.getModel());
        JTableProfesoresExistentes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBanner = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelExit2 = new javax.swing.JPanel();
        lblExit2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombresProf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidosProf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCedulaProf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEspecialidadProf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAnioExp = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtUsuarioProf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCorreoProf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPasswConfirm = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblidProfesor = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jDateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        txtPasswordProf = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();
        btnRegistrarProfeNuevo = new javax.swing.JButton();
        btnEditarProfe = new javax.swing.JButton();
        btnEliminarProfe = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableProfesoresExistentes = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBanner.setBackground(new java.awt.Color(122, 72, 221));
        jPanelBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Administracion Profesores");
        jPanelBanner.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("PROFESORES");
        jPanelBanner.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanelExit2.setBackground(new java.awt.Color(122, 72, 221));

        lblExit2.setBackground(new java.awt.Color(33, 45, 62));
        lblExit2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblExit2.setForeground(new java.awt.Color(255, 255, 255));
        lblExit2.setText("X");
        lblExit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExit2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelExit2Layout = new javax.swing.GroupLayout(jPanelExit2);
        jPanelExit2.setLayout(jPanelExit2Layout);
        jPanelExit2Layout.setHorizontalGroup(
            jPanelExit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExit2Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(lblExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelExit2Layout.setVerticalGroup(
            jPanelExit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanelBanner.add(jPanelExit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/teacher.png.png"))); // NOI18N
        jPanelBanner.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        getContentPane().add(jPanelBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 70));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombres:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        jPanel1.add(txtNombresProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 170, -1));

        jLabel2.setText("Apellidos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jPanel1.add(txtApellidosProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 170, -1));

        jLabel3.setText("Cédula:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        jPanel1.add(txtCedulaProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 170, -1));

        jLabel4.setText("Especialidad:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));
        jPanel1.add(txtEspecialidadProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 170, -1));

        jLabel5.setText("Años de Experiencia:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));
        jPanel1.add(txtAnioExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 93, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 520, 10));

        jLabel6.setText("Usuario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));
        jPanel1.add(txtUsuarioProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 170, -1));

        jLabel7.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel7.setText("CREDENCIALES");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel8.setText("Correo Electronico:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));
        jPanel1.add(txtCorreoProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 170, -1));

        jLabel9.setText("Contraseña:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel12.setText("Confirme su contraseña:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));
        jPanel1.add(txtPasswConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 170, -1));

        jLabel13.setText("ID:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblidProfesor.setText("#");
        jPanel1.add(lblidProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, -1));

        jLabel14.setText("Fecha Nacimiento:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jDateFechaNacimiento.setDateFormatString("yyyy/MM/dd HH:mm:ss");
        jDateFechaNacimiento.setFocusable(false);
        jPanel1.add(jDateFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 140, -1));
        jPanel1.add(txtPasswordProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 570, 330));

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 115, 45));

        btnRegistrarProfeNuevo.setBackground(new java.awt.Color(153, 255, 102));
        btnRegistrarProfeNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarProfeNuevo.setText("REGISTRAR");
        btnRegistrarProfeNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProfeNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarProfeNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 115, 45));

        btnEditarProfe.setText("EDITAR");
        btnEditarProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProfeActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarProfe, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 115, 45));

        btnEliminarProfe.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarProfe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarProfe.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProfe.setText("ELIMINAR");
        btnEliminarProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProfeActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarProfe, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 115, 45));

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 115, 33));

        JTableProfesoresExistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_PROFESOR", "NOMBRES", "APELLIDOS", "CEDULA", "CORREO", "ESPECIALIDAD", "EXPERIENCIA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableProfesoresExistentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableProfesoresExistentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableProfesoresExistentes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 780, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseClicked
        this.dispose();
    }//GEN-LAST:event_lblExit2MouseClicked

    private void lblExit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseEntered
        jPanelExit2.setBackground(Color.red);
        lblExit2.setBackground(Color.white);
    }//GEN-LAST:event_lblExit2MouseEntered

    private void lblExit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseExited
        jPanelExit2.setBackground(new Color(122, 72, 221));
    }//GEN-LAST:event_lblExit2MouseExited

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        frmProfesoresAlcaide profeAlc = new frmProfesoresAlcaide();
        this.dispose();
        profeAlc.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarProfeNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProfeNuevoActionPerformed

        try {
            // Obtener los valores de los campos de texto
            String cedulaProf = txtCedulaProf.getText();
            String codigoProfesor = "#P0001";
            String cedula = txtCedulaProf.getText();
            String nombres = txtNombresProf.getText();
            String apellidos = txtApellidosProf.getText();
            String correo = txtCorreoProf.getText();
            String usuario = txtUsuarioProf.getText();
            char[] password = txtPasswordProf.getPassword();
            String contra= new String(password);
            String especialidad = txtEspecialidadProf.getText();
            int experiencia = Integer.parseInt(txtAnioExp.getText());
            Date FechaNac=jDateFechaNacimiento.getDate();

            // Crear la instancia de Profesor
            Profesor profesor = new Profesor(codigoProfesor, especialidad, experiencia, cedula, nombres, apellidos, usuario, contra, correo,FechaNac);
            codigoProfesor = profesor.GenerarIdProfesor(cedula);
            profesor.setCodigoProfesor(codigoProfesor);//asignar el id generado
            // Guardar los datos en la base de datos
            ctrlRegistroNuevoProfe registro = new ctrlRegistroNuevoProfe();
            registro.RegistrarNuevoProfe(profesor);

            // Mostrar mensaje al usuario
            JOptionPane.showMessageDialog(this, "Los datos se han añadido correctamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos: " + e.getMessage());
        }
        // Actualizar la tabla de profesores (si es necesario)
        controlador.cargarDatosProfesores((DefaultTableModel) JTableProfesoresExistentes.getModel());

    }//GEN-LAST:event_btnRegistrarProfeNuevoActionPerformed

    private void btnEditarProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProfeActionPerformed
        // Obtener los datos del profesor a editar
        String idProfesor = lblidProfesor.getText();
        String nuevosNombres = txtNombresProf.getText();
        String nuevosApellidos = txtApellidosProf.getText();
        String nuevaCedula = txtCedulaProf.getText();
        String nuevoCorreo = txtCorreoProf.getText();
        String nuevaEspecialidad = txtEspecialidadProf.getText();
        String nuevoUsuario=txtUsuarioProf.getText();
        char[] password = txtPasswordProf.getPassword();
        String NuevaContra= new String(password);
        int nuevaExperiencia = Integer.parseInt(txtAnioExp.getText());
        Date FechaNac=jDateFechaNacimiento.getDate();

    // Verificar que los campos no estén vacíos
        if (idProfesor.isEmpty() || nuevosNombres.isEmpty() || nuevosApellidos.isEmpty() || nuevaCedula.isEmpty() || nuevoCorreo.isEmpty() || nuevaEspecialidad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Detener la ejecución del método
        }

    // Llamar al método editarProfesor para realizar la edición
        controlador.editarProfesor(idProfesor, nuevosNombres, nuevosApellidos, nuevaCedula, nuevoCorreo, nuevaEspecialidad, nuevaExperiencia,nuevoUsuario,NuevaContra,FechaNac);

    // Actualizar la tabla de profesores con los datos actualizados
        DefaultTableModel modeloTabla = (DefaultTableModel) JTableProfesoresExistentes.getModel();
        modeloTabla.setRowCount(0); // Limpiar los datos existentes en la tabla
        controlador.cargarDatosProfesores(modeloTabla);

    // Mostrar un mensaje de éxito
        JOptionPane.showMessageDialog(this, "Profesor editado correctamente", "Edición exitosa", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnEditarProfeActionPerformed

    private void btnEliminarProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProfeActionPerformed
        // Obtener el ID del profesor seleccionado
        String idProfesor = lblidProfesor.getText();
        // Llamar al método eliminarProfesor del controlador
        controlador.eliminarProfesor(idProfesor);
        limpiarInputs();
        // Actualizar la tabla de profesores (si es necesario)
        controlador.cargarDatosProfesores((DefaultTableModel) JTableProfesoresExistentes.getModel());
    }//GEN-LAST:event_btnEliminarProfeActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarInputs();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void JTableProfesoresExistentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableProfesoresExistentesMouseClicked
        int filaSeleccionada = JTableProfesoresExistentes.getSelectedRow();
        List<Profesor> profesores = controlador.cargarDatosProfesores((DefaultTableModel) JTableProfesoresExistentes.getModel());
        // Obtener el profesor seleccionado de la lista
        Profesor profesor = profesores.get(filaSeleccionada);

        // Obtener los datos del profesor
        String idProfesor = profesor.getCodigoProfesor();
        String nombres = profesor.getNombres();
        String apellidos = profesor.getApellidos();
        String cedula = profesor.getCedula();
        String correo = profesor.getCorreo();
        String especialidad = profesor.getEspecialidad();
        int experiencia = profesor.getAñosExperiencia();
        String usuario = profesor.getUser();
        String contrasena = profesor.getPassword();

        // Establecer los datos en los campos de texto
        lblidProfesor.setText(idProfesor);
        txtNombresProf.setText(nombres);
        txtApellidosProf.setText(apellidos);
        txtCedulaProf.setText(cedula);
        txtCedulaProf.setEditable(false);
        txtCorreoProf.setText(correo);
        txtEspecialidadProf.setText(especialidad);
        txtAnioExp.setText("" + experiencia);
        txtUsuarioProf.setText(usuario);
        txtPasswordProf.setText(contrasena);
        txtPasswConfirm.setText(contrasena);
    }//GEN-LAST:event_JTableProfesoresExistentesMouseClicked
    private void limpiarInputs() {
        txtNombresProf.setText("");
        txtApellidosProf.setText("");
        txtCedulaProf.setText("");
        txtEspecialidadProf.setText("");
        txtAnioExp.setText("");
        txtUsuarioProf.setText("");
        txtCorreoProf.setText("");
        txtPasswordProf.setText("");
        txtPasswConfirm.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCreateNewProfe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCreateNewProfe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCreateNewProfe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCreateNewProfe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCreateNewProfe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableProfesoresExistentes;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarProfe;
    private javax.swing.JButton btnEliminarProfe;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrarProfeNuevo;
    private com.toedter.calendar.JDateChooser jDateFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBanner;
    private javax.swing.JPanel jPanelExit2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblExit2;
    private javax.swing.JLabel lblidProfesor;
    private javax.swing.JTextField txtAnioExp;
    private javax.swing.JTextField txtApellidosProf;
    private javax.swing.JTextField txtCedulaProf;
    private javax.swing.JTextField txtCorreoProf;
    private javax.swing.JTextField txtEspecialidadProf;
    private javax.swing.JTextField txtNombresProf;
    private javax.swing.JTextField txtPasswConfirm;
    private javax.swing.JPasswordField txtPasswordProf;
    private javax.swing.JTextField txtUsuarioProf;
    // End of variables declaration//GEN-END:variables
}
