/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTAS;


import CONTROLADOR.ctrlRegistroReclusos;
import MODELO.Actividad;
import MODELO.Recluso;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yordan
 */
public class frmCreateNewRecluso extends javax.swing.JFrame {

    /**
     * Creates new form frmCreateNewProfe
     */
    private ctrlRegistroReclusos controlador;

    public frmCreateNewRecluso() {
        initComponents();
        controlador = new ctrlRegistroReclusos(); // Inicializar la instancia de la clase controladora
        controlador.cargarDatosRecluso((DefaultTableModel) JTableReclusosExistentes.getModel());
        JTableReclusosExistentes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBanner = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelExit2 = new javax.swing.JPanel();
        lblExit2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombresReo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidosReo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCedulaReo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAniosCondena = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDelitoReo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtUsuarioReo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCorreoReo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_idRecluso = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CmbConductaReo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jDateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        txtPasswordReo = new javax.swing.JPasswordField();
        txtPasswConfirmReo = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();
        btnRegistrarReclusoNuevo = new javax.swing.JButton();
        btnEditarReo = new javax.swing.JButton();
        btnEliminarReo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableReclusosExistentes = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBanner.setBackground(new java.awt.Color(122, 72, 221));
        jPanelBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Administracion Reclusos");
        jPanelBanner.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("RECLUSOS");
        jPanelBanner.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanelExit2.setBackground(new java.awt.Color(122, 72, 221));

        lblExit2.setBackground(new java.awt.Color(33, 45, 62));
        lblExit2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblExit2.setForeground(new java.awt.Color(255, 255, 255));
        lblExit2.setText("X");
        lblExit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExit2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelExit2Layout = new javax.swing.GroupLayout(jPanelExit2);
        jPanelExit2.setLayout(jPanelExit2Layout);
        jPanelExit2Layout.setHorizontalGroup(
            jPanelExit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExit2Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(lblExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelExit2Layout.setVerticalGroup(
            jPanelExit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanelBanner.add(jPanelExit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/prison.png"))); // NOI18N
        jPanelBanner.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        getContentPane().add(jPanelBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 70));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombres:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));
        jPanel1.add(txtNombresReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, -1));

        jLabel2.setText("Apellidos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));
        jPanel1.add(txtApellidosReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 170, -1));

        jLabel3.setText("Cédula:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        jPanel1.add(txtCedulaReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 170, -1));

        jLabel4.setText("Tiempo Condena (Años):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel1.add(txtAniosCondena, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 80, -1));

        jLabel5.setText("Delito:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, 20));
        jPanel1.add(txtDelitoReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 170, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 580, 10));

        jLabel6.setText("Usuario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));
        jPanel1.add(txtUsuarioReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 170, -1));

        jLabel7.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel7.setText("CREDENCIALES");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel8.setText("Correo Electronico:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));
        jPanel1.add(txtCorreoReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 170, -1));

        jLabel9.setText("Contraseña:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        jLabel12.setText("Confirme su contraseña:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jLabel13.setText("ID:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_idRecluso.setText("#");
        jPanel1.add(lbl_idRecluso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, -1));

        jLabel14.setText("Conducta:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, 20));

        CmbConductaReo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "Buena", "Regular", "Mala" }));
        jPanel1.add(CmbConductaReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 130, -1));

        jLabel15.setText("Fecha Nacimiento:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jDateFechaNacimiento.setDateFormatString("yyyy/MM/dd HH:mm:ss");
        jDateFechaNacimiento.setFocusable(false);
        jPanel1.add(jDateFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 140, -1));

        txtPasswordReo.setText("jPasswordField1");
        jPanel1.add(txtPasswordReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 170, -1));

        txtPasswConfirmReo.setText("jPasswordField1");
        jPanel1.add(txtPasswConfirmReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 650, 350));

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 115, 45));

        btnRegistrarReclusoNuevo.setBackground(new java.awt.Color(153, 255, 102));
        btnRegistrarReclusoNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarReclusoNuevo.setText("REGISTRAR");
        btnRegistrarReclusoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarReclusoNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarReclusoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 115, 45));

        btnEditarReo.setText("MODIFICAR");
        btnEditarReo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarReoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 115, 45));

        btnEliminarReo.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarReo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarReo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarReo.setText("ELIMINAR");
        btnEliminarReo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarReoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 115, 45));

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 115, 33));

        JTableReclusosExistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_RECLCUSO", "NOMBRES", "APELLIDOS", "CEDULA", "CORREO", "DELITO", "TIEMPO_CONDENA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableReclusosExistentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableReclusosExistentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableReclusosExistentes);
        if (JTableReclusosExistentes.getColumnModel().getColumnCount() > 0) {
            JTableReclusosExistentes.getColumnModel().getColumn(0).setResizable(false);
            JTableReclusosExistentes.getColumnModel().getColumn(0).setPreferredWidth(50);
            JTableReclusosExistentes.getColumnModel().getColumn(1).setResizable(false);
            JTableReclusosExistentes.getColumnModel().getColumn(2).setResizable(false);
            JTableReclusosExistentes.getColumnModel().getColumn(3).setResizable(false);
            JTableReclusosExistentes.getColumnModel().getColumn(4).setResizable(false);
            JTableReclusosExistentes.getColumnModel().getColumn(5).setResizable(false);
            JTableReclusosExistentes.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 860, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseClicked
        this.dispose();
    }//GEN-LAST:event_lblExit2MouseClicked

    private void lblExit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseEntered
        jPanelExit2.setBackground(Color.red);
        lblExit2.setBackground(Color.white);
    }//GEN-LAST:event_lblExit2MouseEntered

    private void lblExit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseExited
        jPanelExit2.setBackground(new Color(122, 72, 221));
    }//GEN-LAST:event_lblExit2MouseExited

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        frmProfesoresAlcaide profeAlc = new frmProfesoresAlcaide();
        this.dispose();
        profeAlc.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarReclusoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarReclusoNuevoActionPerformed

        try {
            // Obtener los valores de los campos de texto
            String cedulaRecluso= txtCedulaReo.getText();
            String codigoRecluso = "#R0001";
            String cedula = txtCedulaReo.getText();
            String nombres = txtNombresReo.getText();
            String apellidos = txtApellidosReo.getText();
            String correo = txtCorreoReo.getText();
            String usuario = txtUsuarioReo.getText();
            char[] password = txtPasswordReo.getPassword();
            String contra= new String(password);
            int TimeCondena = Integer.parseInt(txtAniosCondena.getText());
            String delito = txtDelitoReo.getText();
            String conducta = (String) CmbConductaReo.getSelectedItem();
            Date fechaNac=jDateFechaNacimiento.getDate();

            // Crear la instancia de Recluso
            Recluso recluso = new Recluso(codigoRecluso, TimeCondena, delito, conducta, cedula, nombres, apellidos, usuario, contra, correo,fechaNac);
            codigoRecluso = recluso.GenerarIdRecluso(cedula);
            recluso.setCodigoRecluso(codigoRecluso);//asignar el id generado
            // Crear el mensaje de confirmación
            String mensaje = "¿Deseas Registar al recluso: " + recluso.getNombres()+" "+ recluso.getApellidos()+ "?";
            int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Confirmar Resgistro", JOptionPane.YES_NO_OPTION);
            // Verificar la opción seleccionada
            if (opcion == JOptionPane.YES_OPTION) {
                // Guardar los datos en la base de datos
                 controlador.RegistrarNuevoRecluso(recluso);
                limpiarInputs();
            } else {
                // Detener el evento
                return;
            }
            

            // Mostrar mensaje al usuario
            JOptionPane.showMessageDialog(this, "Los datos se han añadido correctamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos: " + e.getMessage());
        }
        // Actualizar la tabla de profesores (si es necesario)
        controlador.cargarDatosRecluso((DefaultTableModel) JTableReclusosExistentes.getModel());

    }//GEN-LAST:event_btnRegistrarReclusoNuevoActionPerformed

    private void btnEditarReoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarReoActionPerformed
        // Obtener los datos del profesor a editar
            String cedulaRecluso= txtCedulaReo.getText();
            String codigoRecluso = lbl_idRecluso.getText();
            String cedula = txtCedulaReo.getText();
            String nombres = txtNombresReo.getText();
            String apellidos = txtApellidosReo.getText();
            String correo = txtCorreoReo.getText();
            String usuario = txtUsuarioReo.getText();
            char[] password = txtPasswordReo.getPassword();
            String Nuevacontra= new String(password);
            int TimeCondena = Integer.parseInt(txtAniosCondena.getText());
            String delito = txtDelitoReo.getText();
            String conducta = (String) CmbConductaReo.getSelectedItem();
            Date fechaNac=jDateFechaNacimiento.getDate();

        // Verificar que los campos no estén vacíos
        if (codigoRecluso.isEmpty() || nombres.isEmpty() || apellidos.isEmpty() || cedula.isEmpty() || correo.isEmpty() || usuario.isEmpty()|| Nuevacontra.isEmpty()
                || (""+TimeCondena).isEmpty()|| delito.isEmpty()|| conducta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Detener la ejecución del método
        }
        // Crear la instancia de Recluso
            Recluso recluso = new Recluso(codigoRecluso, TimeCondena, delito, conducta, cedula, nombres, apellidos, usuario, Nuevacontra, correo,fechaNac);
            // Crear el mensaje de confirmación
            String mensaje = "¿Deseas Modificar al recluso: " + recluso.getNombres()+" "+ recluso.getApellidos()+ "?";
            int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Confirmar Resgistro", JOptionPane.YES_NO_OPTION);
            // Verificar la opción seleccionada
            if (opcion == JOptionPane.YES_OPTION) {
                // Guardar los datos en la base de datos
                 controlador.EditarRecluso(recluso);
                limpiarInputs();
            } else {
                // Detener el evento
                return;
            }
        // Actualizar la tabla de profesores con los datos actualizados
        DefaultTableModel modeloTabla = (DefaultTableModel) JTableReclusosExistentes.getModel();
        modeloTabla.setRowCount(0); // Limpiar los datos existentes en la tabla
        controlador.cargarDatosRecluso(modeloTabla);

        // Mostrar un mensaje de éxito
        JOptionPane.showMessageDialog(this, "Profesor editado correctamente", "Edición exitosa", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnEditarReoActionPerformed

    private void btnEliminarReoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarReoActionPerformed
        // Obtener el ID del profesor seleccionado
        String idRecluso = lbl_idRecluso.getText();
        String nombreReo=txtNombresReo.getText()+" "+ txtApellidosReo.getText();
        limpiarInputs();
        // Crear el mensaje de confirmación
            String mensaje = "¿Deseas Eliminar al recluso: " + nombreReo+ " ?";
            int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Confirmar Resgistro", JOptionPane.YES_NO_OPTION);
            // Verificar la opción seleccionada
            if (opcion == JOptionPane.YES_OPTION) {
                // Llamar al método eliminarProfesor del controlador
                controlador.eliminarRecluso(idRecluso);
                limpiarInputs();
            } else {
                // Detener el evento
                return;
            }
        // Actualizar la tabla de profesores (si es necesario)
        controlador.cargarDatosRecluso((DefaultTableModel) JTableReclusosExistentes.getModel());
    }//GEN-LAST:event_btnEliminarReoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarInputs();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void JTableReclusosExistentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableReclusosExistentesMouseClicked
        int filaSeleccionada = JTableReclusosExistentes.getSelectedRow();
        List<Recluso> recluso = controlador.cargarDatosRecluso((DefaultTableModel) JTableReclusosExistentes.getModel());
        // Obtener el profesor seleccionado de la lista
        Recluso reo = recluso.get(filaSeleccionada);

        // Obtener los datos del profesor
        String idRecluso = reo.getCodigoRecluso();
        String cedula = reo.getCedula();
        String nombres = reo.getNombres();
        String apellidos = reo.getApellidos();
        int condena = reo.getTiempo_condena();
        String delito = reo.getDelito();
        String conducta = reo.getConducta();
        String correo = reo.getCorreo();
        String usuario = reo.getUser();
        String contrasena = reo.getPassword();

        // Establecer los datos en los campos de texto
        lbl_idRecluso.setText(idRecluso);
        txtNombresReo.setText(nombres);
        txtApellidosReo.setText(apellidos);
        txtCedulaReo.setText(cedula);
        txtCedulaReo.setEditable(false);
        txtCorreoReo.setText(correo);
        txtAniosCondena.setText(""+condena);
        txtDelitoReo.setText(delito);
        CmbConductaReo.setSelectedItem(conducta);
        txtUsuarioReo.setText(usuario);
        txtPasswordReo.setText(contrasena);
        txtPasswConfirmReo.setText(contrasena);
    }//GEN-LAST:event_JTableReclusosExistentesMouseClicked
    private void limpiarInputs() {
        txtNombresReo.setText("");
        txtApellidosReo.setText("");
        txtCedulaReo.setText("");
        txtAniosCondena.setText("");
        txtDelitoReo.setText("");
        txtUsuarioReo.setText("");
        txtCorreoReo.setText("");
        txtPasswordReo.setText("");
        txtPasswConfirmReo.setText("");
        CmbConductaReo.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCreateNewRecluso.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCreateNewRecluso.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCreateNewRecluso.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCreateNewRecluso.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCreateNewRecluso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbConductaReo;
    private javax.swing.JTable JTableReclusosExistentes;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarReo;
    private javax.swing.JButton btnEliminarReo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrarReclusoNuevo;
    private com.toedter.calendar.JDateChooser jDateFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBanner;
    private javax.swing.JPanel jPanelExit2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblExit2;
    private javax.swing.JLabel lbl_idRecluso;
    private javax.swing.JTextField txtAniosCondena;
    private javax.swing.JTextField txtApellidosReo;
    private javax.swing.JTextField txtCedulaReo;
    private javax.swing.JTextField txtCorreoReo;
    private javax.swing.JTextField txtDelitoReo;
    private javax.swing.JTextField txtNombresReo;
    private javax.swing.JPasswordField txtPasswConfirmReo;
    private javax.swing.JPasswordField txtPasswordReo;
    private javax.swing.JTextField txtUsuarioReo;
    // End of variables declaration//GEN-END:variables
}
