/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTAS;

import CONTROLADOR.ctrlRegistroNuevoProfe;
import MODELO.AsignacionProfesor;
import MODELO.Profesor;
import javax.swing.JComboBox; // Importa la clase JComboBox
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelo Meza
 */
public class frmProfesoresAlcaide extends javax.swing.JFrame {

    /**
     * Creates new form frmAlcaide
     */
    private ctrlRegistroNuevoProfe controlador;
    private DefaultTableModel modeloTabla;

    public frmProfesoresAlcaide() {
        initComponents();
        lblHandle.setText("admin");
        CmbProfesoresExistentes.removeAllItems();
        JTableAsignacionProfesores.removeAll();
        controlador = new ctrlRegistroNuevoProfe(); // Inicializar la instancia de la clase controladora
        controlador.cargarProfesoresComboBox(CmbProfesoresExistentes);
        controlador.cargarDatosAsignaciones((DefaultTableModel) JTableAsignacionProfesores.getModel());
        JTableAsignacionProfesores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //elementos que solo se visualiazn para Talleres
        lblGrupo.setVisible(false);
        cmbGrupos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackGround = new javax.swing.JPanel();
        jPanelSide = new javax.swing.JPanel();
        btnActividades = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnTalleres = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnProfesores = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnReclusos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblHandle = new javax.swing.JLabel();
        LlbIconUser = new javax.swing.JLabel();
        BtnOpcion5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanelBanner = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelExit2 = new javax.swing.JPanel();
        lblExit2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableAsignacionProfesores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        panelAgregar = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        panelCancelar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        panelEditar = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        panelEliminar = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        lblAcTaller = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPNombre = new javax.swing.JPanel();
        jPCampoNombre = new javax.swing.JPanel();
        jPFecha = new javax.swing.JPanel();
        CmbProfesoresExistentes = new javax.swing.JComboBox<>();
        jPCampoFecha = new javax.swing.JPanel();
        cmbActividadTaller = new javax.swing.JComboBox<>();
        cmbGrupos = new javax.swing.JComboBox<>();
        CmbAsignacionDocente = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        btnRegistrarProfesor = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanelBackGround.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSide.setBackground(new java.awt.Color(54, 33, 89));
        jPanelSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActividades.setBackground(new java.awt.Color(64, 43, 100));
        btnActividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActividadesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActividadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActividadesMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("ACTIVIDADES");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/list.png"))); // NOI18N

        javax.swing.GroupLayout btnActividadesLayout = new javax.swing.GroupLayout(btnActividades);
        btnActividades.setLayout(btnActividadesLayout);
        btnActividadesLayout.setHorizontalGroup(
            btnActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActividadesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel9))
        );
        btnActividadesLayout.setVerticalGroup(
            btnActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActividadesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnActividadesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9))
        );

        jPanelSide.add(btnActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 290, 50));

        btnTalleres.setBackground(new java.awt.Color(64, 43, 100));
        btnTalleres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTalleres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTalleresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTalleresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTalleresMouseExited(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("TALLERES");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/group.png"))); // NOI18N

        javax.swing.GroupLayout btnTalleresLayout = new javax.swing.GroupLayout(btnTalleres);
        btnTalleres.setLayout(btnTalleresLayout);
        btnTalleresLayout.setHorizontalGroup(
            btnTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTalleresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4))
        );
        btnTalleresLayout.setVerticalGroup(
            btnTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTalleresLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnTalleresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4))
        );

        jPanelSide.add(btnTalleres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, 50));

        btnProfesores.setBackground(new java.awt.Color(85, 65, 118));
        btnProfesores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfesoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProfesoresMouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/teacher.png.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("PROFESORES");

        javax.swing.GroupLayout btnProfesoresLayout = new javax.swing.GroupLayout(btnProfesores);
        btnProfesores.setLayout(btnProfesoresLayout);
        btnProfesoresLayout.setHorizontalGroup(
            btnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProfesoresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel6))
        );
        btnProfesoresLayout.setVerticalGroup(
            btnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProfesoresLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnProfesoresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6))
        );

        jPanelSide.add(btnProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 290, 50));

        btnReclusos.setBackground(new java.awt.Color(64, 43, 100));
        btnReclusos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReclusos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReclusosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReclusosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReclusosMouseExited(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/prison.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("RECLUSOS");

        javax.swing.GroupLayout btnReclusosLayout = new javax.swing.GroupLayout(btnReclusos);
        btnReclusos.setLayout(btnReclusosLayout);
        btnReclusosLayout.setHorizontalGroup(
            btnReclusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReclusosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel8))
        );
        btnReclusosLayout.setVerticalGroup(
            btnReclusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReclusosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnReclusosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8))
        );

        jPanelSide.add(btnReclusos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 290, 50));

        lblHandle.setBackground(new java.awt.Color(204, 204, 204));
        lblHandle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHandle.setForeground(new java.awt.Color(204, 204, 204));
        lblHandle.setText("USER");
        jPanelSide.add(lblHandle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        LlbIconUser.setForeground(new java.awt.Color(153, 153, 153));
        LlbIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/UserIconBanner.png"))); // NOI18N
        jPanelSide.add(LlbIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 40));

        BtnOpcion5.setBackground(new java.awt.Color(85, 55, 100));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/arrow.png"))); // NOI18N

        lblLogout.setBackground(new java.awt.Color(204, 204, 204));
        lblLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(204, 204, 204));
        lblLogout.setText("Log Out");
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BtnOpcion5Layout = new javax.swing.GroupLayout(BtnOpcion5);
        BtnOpcion5.setLayout(BtnOpcion5Layout);
        BtnOpcion5Layout.setHorizontalGroup(
            BtnOpcion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnOpcion5Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogout)
                .addGap(12, 12, 12))
        );
        BtnOpcion5Layout.setVerticalGroup(
            BtnOpcion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnOpcion5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogout)
                .addGap(14, 14, 14))
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelSide.add(BtnOpcion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 290, 50));

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 230, 20));

        jTextField1.setBackground(new java.awt.Color(54, 33, 89));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("ADMINISTRADOR");
        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField1.setFocusable(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 180, 40));

        jLabel1.setBackground(new java.awt.Color(54, 33, 89));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ROL:");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jPanelSide.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 220, 40));

        jPanelBackGround.add(jPanelSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, -1));

        jPanelBanner.setBackground(new java.awt.Color(122, 72, 221));
        jPanelBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("SISTEMA CARCELARIO - Profesores");
        jPanelBanner.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 64, -1, -1));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("ALCAIDE");
        jPanelBanner.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 24, -1, -1));

        jPanelExit2.setBackground(new java.awt.Color(122, 72, 221));

        lblExit2.setBackground(new java.awt.Color(33, 45, 62));
        lblExit2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblExit2.setForeground(new java.awt.Color(255, 255, 255));
        lblExit2.setText("X");
        lblExit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExit2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelExit2Layout = new javax.swing.GroupLayout(jPanelExit2);
        jPanelExit2.setLayout(jPanelExit2Layout);
        jPanelExit2Layout.setHorizontalGroup(
            jPanelExit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExit2Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(lblExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelExit2Layout.setVerticalGroup(
            jPanelExit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanelBanner.add(jPanelExit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/teacher.png.png"))); // NOI18N
        jPanelBanner.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 0, 102));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/sync.png"))); // NOI18N
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        jPanelBanner.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 30, -1));

        jPanelBackGround.add(jPanelBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, 1080, -1));

        JTableAsignacionProfesores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JTableAsignacionProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre del Docente", "ID_Profesor", "Tipo_Asignacion", "Nombre Actividad/Taller", "ID_Actividad/Taller", "Grupo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableAsignacionProfesores.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        JTableAsignacionProfesores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JTableAsignacionProfesores.setGridColor(new java.awt.Color(255, 255, 255));
        JTableAsignacionProfesores.setIntercellSpacing(new java.awt.Dimension(5, 5));
        JTableAsignacionProfesores.getTableHeader().setReorderingAllowed(false);
        JTableAsignacionProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableAsignacionProfesoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableAsignacionProfesores);
        if (JTableAsignacionProfesores.getColumnModel().getColumnCount() > 0) {
            JTableAsignacionProfesores.getColumnModel().getColumn(0).setResizable(false);
            JTableAsignacionProfesores.getColumnModel().getColumn(0).setPreferredWidth(75);
            JTableAsignacionProfesores.getColumnModel().getColumn(1).setResizable(false);
            JTableAsignacionProfesores.getColumnModel().getColumn(1).setPreferredWidth(200);
            JTableAsignacionProfesores.getColumnModel().getColumn(2).setResizable(false);
            JTableAsignacionProfesores.getColumnModel().getColumn(2).setPreferredWidth(100);
            JTableAsignacionProfesores.getColumnModel().getColumn(3).setResizable(false);
            JTableAsignacionProfesores.getColumnModel().getColumn(3).setPreferredWidth(200);
            JTableAsignacionProfesores.getColumnModel().getColumn(4).setResizable(false);
            JTableAsignacionProfesores.getColumnModel().getColumn(4).setPreferredWidth(150);
            JTableAsignacionProfesores.getColumnModel().getColumn(5).setResizable(false);
            JTableAsignacionProfesores.getColumnModel().getColumn(5).setPreferredWidth(200);
            JTableAsignacionProfesores.getColumnModel().getColumn(6).setResizable(false);
            JTableAsignacionProfesores.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        jPanelBackGround.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 1080, 290));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("ID");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 22, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 14, 220));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 217, 400, 10));

        panelAgregar.setBackground(new java.awt.Color(204, 204, 204));
        panelAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelAgregar.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/diskette.png"))); // NOI18N
        panelAgregar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 43, -1));

        jPanel2.add(panelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        panelCancelar.setBackground(new java.awt.Color(204, 204, 204));
        panelCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelCancelar.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/cancel.png"))); // NOI18N
        panelCancelar.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 43, -1));

        jPanel2.add(panelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 138, -1));

        panelEditar.setBackground(new java.awt.Color(204, 204, 204));
        panelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEditar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panelEditar.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/editing.png"))); // NOI18N
        panelEditar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 43, -1));

        jPanel2.add(panelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, -1, -1));

        panelEliminar.setBackground(new java.awt.Color(204, 204, 204));
        panelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelEliminar.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/bin.png"))); // NOI18N
        panelEliminar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 43, -1));

        jPanel2.add(panelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, -1, -1));

        lblAcTaller.setText("Actividad o Taller:");
        jPanel2.add(lblAcTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 77, -1, -1));

        lblGrupo.setText("Grupo:");
        jPanel2.add(lblGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 105, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 21, -1, -1));

        jPNombre.setBackground(new java.awt.Color(204, 204, 204));
        jPNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 56, 210, -1));

        jPCampoNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPCampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 49, -1, -1));

        jPFecha.setBackground(new java.awt.Color(204, 204, 204));
        jPFecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CmbProfesoresExistentes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbProfesoresExistentesItemStateChanged(evt);
            }
        });
        jPFecha.add(CmbProfesoresExistentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, -1));

        jPanel2.add(jPFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 137, 215, 35));

        jPCampoFecha.setBackground(new java.awt.Color(204, 204, 204));
        jPCampoFecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPCampoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 78, -1, 38));

        cmbActividadTaller.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbActividadTallerItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbActividadTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 158, -1));

        jPanel2.add(cmbGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 133, -1));

        CmbAsignacionDocente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "Actividad", "Taller" }));
        CmbAsignacionDocente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbAsignacionDocenteItemStateChanged(evt);
            }
        });
        jPanel2.add(CmbAsignacionDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 190, 180, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Asignacion:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 186, 80, -1));

        lblID.setBackground(new java.awt.Color(255, 255, 255));
        lblID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 43, 20));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Profesor:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 137, -1, 17));

        jLabel17.setText("Edad:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 46, -1, -1));
        jPanel2.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 50, 10));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/AdminReo.png"))); // NOI18N

        btnRegistrarProfesor.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRegistrarProfesor.setText("ADM. PROFESORES");
        btnRegistrarProfesor.setMaximumSize(new java.awt.Dimension(149, 23));
        btnRegistrarProfesor.setMinimumSize(new java.awt.Dimension(149, 23));
        btnRegistrarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 230, 70));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 167, 670, 10));

        jPanelBackGround.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 1100, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 1367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExit2MouseClicked

    private void lblExit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseEntered
        jPanelExit2.setBackground(Color.red);
        lblExit2.setBackground(Color.white);
    }//GEN-LAST:event_lblExit2MouseEntered

    private void lblExit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseExited
        jPanelExit2.setBackground(new Color(122, 72, 221));
    }//GEN-LAST:event_lblExit2MouseExited

    private void btnActividadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActividadesMouseExited
        resetColor(btnActividades);
        resetColor(btnTalleres);
        setColor(btnProfesores);
        resetColor(btnReclusos);

    }//GEN-LAST:event_btnActividadesMouseExited

    private void btnTalleresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTalleresMouseExited
        resetColor(btnActividades);
        resetColor(btnTalleres);
        setColor(btnProfesores);
        resetColor(btnReclusos);
    }//GEN-LAST:event_btnTalleresMouseExited

    private void btnProfesoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesoresMouseExited
        resetColor(btnActividades);
        resetColor(btnTalleres);
        setColor(btnProfesores);
        resetColor(btnReclusos);    }//GEN-LAST:event_btnProfesoresMouseExited

    private void btnReclusosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReclusosMouseExited
        resetColor(btnActividades);
        resetColor(btnTalleres);
        setColor(btnProfesores);
        resetColor(btnReclusos);    }//GEN-LAST:event_btnReclusosMouseExited

    private void btnActividadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActividadesMouseEntered
        setColor(btnActividades);
        resetColor(btnTalleres);
        resetColor(btnProfesores);
        resetColor(btnReclusos);
    }//GEN-LAST:event_btnActividadesMouseEntered

    private void btnTalleresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTalleresMouseEntered
        setColor(btnTalleres);
        resetColor(btnActividades);
        resetColor(btnProfesores);
        resetColor(btnReclusos);
    }//GEN-LAST:event_btnTalleresMouseEntered

    private void btnProfesoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesoresMouseEntered
        setColor(btnProfesores);
        resetColor(btnTalleres);
        resetColor(btnActividades);
        resetColor(btnReclusos);
    }//GEN-LAST:event_btnProfesoresMouseEntered

    private void btnReclusosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReclusosMouseEntered
        setColor(btnReclusos);
        resetColor(btnTalleres);
        resetColor(btnProfesores);
        resetColor(btnActividades);
    }//GEN-LAST:event_btnReclusosMouseEntered

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // Mostrar mensaje de confirmación para cerrar sesión
        int opcion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas cerrar sesión?", "Cerrar sesión", JOptionPane.YES_NO_OPTION);

        // Verificar la opción seleccionada por el usuario
        if (opcion == JOptionPane.YES_OPTION) {
            // Mostrar mensaje de sesión cerrada con éxito
            JOptionPane.showMessageDialog(null, "Sesión cerrada con éxito", "Sesión cerrada", JOptionPane.INFORMATION_MESSAGE);

            // Cerrar el formulario actual
            this.dispose();

            // Cargar el formulario de login
            Login loginForm = new Login();
            loginForm.setVisible(true);
        }

    }//GEN-LAST:event_lblLogoutMouseClicked

    private void btnActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActividadesMouseClicked
        frmAlcaide Alcaide = new frmAlcaide();
        this.dispose();
        Alcaide.setVisible(true);
    }//GEN-LAST:event_btnActividadesMouseClicked

    private void btnTalleresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTalleresMouseClicked
        frmTalleresAlcaide TalleresA = new frmTalleresAlcaide();
        this.dispose();
        TalleresA.setVisible(true);
    }//GEN-LAST:event_btnTalleresMouseClicked

    private void btnReclusosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReclusosMouseClicked
        frmReclusosAlcaide ReclusosA = new frmReclusosAlcaide();
        this.dispose();
        ReclusosA.setVisible(true);
    }//GEN-LAST:event_btnReclusosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int asignaciones = controlador.consultarAsignacionesProfesor(lblID.getText());
        if (lblID.getText().isEmpty() || CmbProfesoresExistentes.getSelectedIndex() == 0
                || cmbActividadTaller.getSelectedIndex() == 0 || CmbAsignacionDocente.getSelectedIndex() == 0
                || lblEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No ha selecionado una asignacion, por favor seleccione alguna de la tabla.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        } else if (asignaciones == 0) {
            JOptionPane.showMessageDialog(this,
                    "No existen Asignaciones aun\n"
                    + "Cree primero un asignacion para poder eliminar.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener los datos del asigancion a editar
        DefaultTableModel modeloTabla = (DefaultTableModel) JTableAsignacionProfesores.getModel();//modelo para obetner IDasignacion
        int filaSeleccionada = JTableAsignacionProfesores.getSelectedRow();
        String idAsignacion = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
        String idDocente = lblID.getText();
        String Nuevo_nombreDocente = (String) CmbProfesoresExistentes.getSelectedItem();
        String Nuevo_tipoAsignacion = (String) CmbAsignacionDocente.getSelectedItem();
        String Nuevo_nombreActividadTaller = (String) cmbActividadTaller.getSelectedItem();
        String Nuevo_nombreGrupo = (String) cmbGrupos.getSelectedItem();
        String Nuevo_idActividadTaller = "";
        if (Nuevo_tipoAsignacion.equals("Actividad")) {
            Nuevo_idActividadTaller = controlador.ObtenerActividad(Nuevo_nombreActividadTaller);
        } else if (Nuevo_tipoAsignacion.equals("Taller")) {
            Nuevo_idActividadTaller = controlador.ObtenerTaller(Nuevo_nombreActividadTaller);
        }
        AsignacionProfesor asignacion = new AsignacionProfesor(idAsignacion, idDocente, Nuevo_nombreDocente,
                Nuevo_tipoAsignacion, Nuevo_nombreActividadTaller, Nuevo_idActividadTaller, Nuevo_nombreGrupo);

        // Crear el mensaje de confirmación
        String mensaje = "¿Deseas Editar la asignación con ID: " + idAsignacion + "?";
        int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        // Verificar la opción seleccionada
        if (opcion == JOptionPane.YES_OPTION) {
            // Llamar al método eliminarAsignacion del controlador
            controlador.editarAsignacion(asignacion);
            limpiarInputs();
        } else {
            // Detener el evento
            return;
        }
        // Actualizar la tabla de Asignaciones con los datos actualizados
        modeloTabla.setRowCount(0); // Limpiar los datos existentes en la tabla
        controlador.cargarDatosAsignaciones(modeloTabla);

        // Mostrar un mensaje de éxito
        JOptionPane.showMessageDialog(this, "Asignacion editada correctamente", "Edición exitosa", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // cuando de click se limpian los input
        limpiarInputs();
        //actualizar tabla
        DefaultTableModel modeloTabla = (DefaultTableModel) JTableAsignacionProfesores.getModel();
        modeloTabla.setRowCount(0); // Limpiar los datos existentes en la tabla
        controlador.cargarDatosAsignaciones(modeloTabla);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        if (lblID.getText().isEmpty() || CmbProfesoresExistentes.getSelectedIndex() == 0
                || cmbActividadTaller.getSelectedIndex() == 0 || CmbAsignacionDocente.getSelectedIndex() == 0
                || lblEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Existen campos vacios,\npor favor seleccione los datos correctos.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Obtener los valores necesarios para la asignación desde los campos de la interfaz
        String idDocente = lblID.getText();
        String nombreDocente = (String) CmbProfesoresExistentes.getSelectedItem();
        String tipoAsignacion = (String) CmbAsignacionDocente.getSelectedItem();
        String nombreActividadTaller = (String) cmbActividadTaller.getSelectedItem();
        String nombreGrupo = (String) cmbGrupos.getSelectedItem();
        String idActividadTaller = "";
        if (tipoAsignacion.equals("Actividad")) {
            idActividadTaller = controlador.ObtenerActividad(nombreActividadTaller);
        } else if (tipoAsignacion.equals("Taller")) {
            idActividadTaller = controlador.ObtenerTaller(nombreActividadTaller);
        }
        // Crear el mensaje de confirmación
        String mensaje = "¿Deseas Registar al Profesor: " + nombreDocente + " en " + nombreActividadTaller + " ?";
        int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Confirmar Resgistro", JOptionPane.YES_NO_OPTION);
        // Verificar la opción seleccionada
        if (opcion == JOptionPane.YES_OPTION) {
            // Llamar al método en tu controlador para agregar la asignación de profesor
            controlador.agregarAsignacionProfesor(idDocente, nombreDocente, tipoAsignacion, nombreActividadTaller,
                    idActividadTaller, nombreGrupo);
            limpiarInputs();
        } else {
            // Detener el evento
            return;
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegistrarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProfesorActionPerformed
        frmCreateNewProfe profe = new frmCreateNewProfe();
        profe.setVisible(true);
    }//GEN-LAST:event_btnRegistrarProfesorActionPerformed

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        // limpiar inputs
        limpiarInputs();
        // Actualizar la tabla de Asignaciones con los datos actualizados
        DefaultTableModel modeloTabla = (DefaultTableModel) JTableAsignacionProfesores.getModel();
        modeloTabla.setRowCount(0); // Limpiar los datos existentes en la tabla
        controlador.cargarDatosAsignaciones(modeloTabla);
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void CmbAsignacionDocenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbAsignacionDocenteItemStateChanged
        //Obtener la opcion Selecionada: Actividad o Taller.
        String opcion = (String) CmbAsignacionDocente.getSelectedItem();
        // Verificar la opción seleccionada
        if (opcion.equals("Actividad")) {
            cmbActividadTaller.removeAllItems();
            lblGrupo.setVisible(false);
            cmbGrupos.setVisible(false);
            controlador.cargarActividadesComboBox(cmbActividadTaller);
        } else if (opcion.equals("Taller")) {
            cmbActividadTaller.removeAllItems();
            lblGrupo.setVisible(true);
            cmbGrupos.setVisible(true);
            controlador.cargarTalleresComboBox(cmbActividadTaller);
        }

    }//GEN-LAST:event_CmbAsignacionDocenteItemStateChanged

    private void cmbActividadTallerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbActividadTallerItemStateChanged
        //Obtener la opcion Selecionada: Actividad o Taller.
        String opcion = (String) CmbAsignacionDocente.getSelectedItem();
        // Verificar la opción seleccionada
        if (opcion.equals("Actividad")) {
            cmbGrupos.setSelectedItem(" ");
        } else if (opcion.equals("Taller")) {
            cmbGrupos.removeAllItems();
            String NombreTaller = (String) cmbActividadTaller.getSelectedItem();
            System.out.println(NombreTaller);
            String IdTaller = controlador.ObtenerTaller(NombreTaller);
            System.out.println("elid taller es:" + IdTaller);
            controlador.cargarGruposTalleres(IdTaller, cmbGrupos);
        }

    }//GEN-LAST:event_cmbActividadTallerItemStateChanged

    private void CmbProfesoresExistentesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbProfesoresExistentesItemStateChanged

        String profe = (String) CmbProfesoresExistentes.getSelectedItem();
        List<Profesor> profesores = controlador.cargarDatosProfesores();
        String Idprofe = "";
        int edad = 0;
        for (Profesor profesor : profesores) {
            if ((profesor.getNombres() + " " + profesor.getApellidos()).equalsIgnoreCase(profe)) {
                Idprofe = profesor.getCodigoProfesor();
                edad = profesor.CalcularEdad(profesor.getFechaNacimiento());
            }
        }
        lblID.setText(Idprofe);
        if (edad == 0) {
            lblEdad.setText("");
        } else {
            lblEdad.setText(edad + " años");
        }
    }//GEN-LAST:event_CmbProfesoresExistentesItemStateChanged

    private void JTableAsignacionProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableAsignacionProfesoresMouseClicked

        int filaSeleccionada = JTableAsignacionProfesores.getSelectedRow();
        List<AsignacionProfesor> asignaciones = controlador.cargarDatosAsignaciones((DefaultTableModel) JTableAsignacionProfesores.getModel());
        // Obtener el profesor seleccionado de la lista
        AsignacionProfesor asignacion = asignaciones.get(filaSeleccionada);

        // Obtener los datos del profesor
        String idProfesor = asignacion.getIdDocente();
        String NombreDocente = asignacion.getNombreDocente();
        String tipoAsignacion = asignacion.getTipoAsignacion();
        String Nombre_ActTaller = asignacion.getNombreActividadTaller();
        String idActTaller = asignacion.getIdActividadTaller();
        String NombreGrupo = asignacion.getNombreGrupo();
        String edad = "";

        //Para obtener la edad
        List<Profesor> prof = controlador.cargarDatosProfesores();
        for (Profesor profe : prof) {
            if (profe.getCodigoProfesor().equals(idProfesor)) {
                edad = (profe.CalcularEdad(profe.getFechaNacimiento()) + " años");
            }
        }

        // Establecer los datos en los campos de texto
        lblID.setText("" + idProfesor);
        lblEdad.setText(edad);
        CmbProfesoresExistentes.setSelectedItem(NombreDocente);
        CmbAsignacionDocente.setSelectedItem(tipoAsignacion);
        cmbActividadTaller.setSelectedItem(Nombre_ActTaller);
        cmbGrupos.setSelectedItem(NombreGrupo);
        // Restaurar la selección después de la actualización
        if (filaSeleccionada != -1) {
            JTableAsignacionProfesores.getSelectionModel().setSelectionInterval(filaSeleccionada, filaSeleccionada);
        }
    }//GEN-LAST:event_JTableAsignacionProfesoresMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int asignaciones = controlador.consultarAsignacionesProfesor(lblID.getText());
        if (lblID.getText().isEmpty() || CmbProfesoresExistentes.getSelectedIndex() == 0
                || cmbActividadTaller.getSelectedIndex() == 0 || CmbAsignacionDocente.getSelectedIndex() == 0
                || lblEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No ha selecionado una asignacion, por favor seleccione alguna de la tabla.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        } else if (asignaciones == 0) {
            JOptionPane.showMessageDialog(this,
                    "No existen Asignaciones aun\n"
                    + "Cree primero un asignacion para poder eliminar.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener los datos del asigancion a Eliminar
        DefaultTableModel modeloTabla = (DefaultTableModel) JTableAsignacionProfesores.getModel();//modelo para obetner IDasignacion
        int filaSeleccionada = JTableAsignacionProfesores.getSelectedRow();
        String idAsignacion = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
        System.out.println(idAsignacion);
        // Crear el mensaje de confirmación
        String mensaje = "¿Deseas eliminar la asignación con ID: " + idAsignacion + "?";
        int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        // Verificar la opción seleccionada
        if (opcion == JOptionPane.YES_OPTION) {
            // Llamar al método eliminarAsignacion del controlador
            controlador.eliminarAsignacion(idAsignacion);
            limpiarInputs();
        } else {
            // Detener el evento
            return;
        }

        // Actualizar la tabla de profesores (si es necesario)
        controlador.cargarDatosAsignaciones(modeloTabla);
    }//GEN-LAST:event_btnEliminarActionPerformed
    void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(64, 43, 100));
    }

    void limpiarInputs() {
        lblID.setText("");
        CmbProfesoresExistentes.setSelectedItem("--Seleccione--");
        CmbAsignacionDocente.setSelectedItem("--Seleccione--");
        cmbActividadTaller.setSelectedItem("--Seleccione--");
        if (cmbGrupos.isVisible()) {
            cmbGrupos.setSelectedItem("--Seleccione--");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProfesoresAlcaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProfesoresAlcaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProfesoresAlcaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProfesoresAlcaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProfesoresAlcaide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnOpcion5;
    private javax.swing.JComboBox<String> CmbAsignacionDocente;
    private javax.swing.JComboBox<String> CmbProfesoresExistentes;
    private javax.swing.JTable JTableAsignacionProfesores;
    private javax.swing.JLabel LlbIconUser;
    private javax.swing.JPanel btnActividades;
    private javax.swing.JLabel btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel btnProfesores;
    private javax.swing.JPanel btnReclusos;
    private javax.swing.JButton btnRegistrarProfesor;
    private javax.swing.JPanel btnTalleres;
    private javax.swing.JComboBox<String> cmbActividadTaller;
    private javax.swing.JComboBox<String> cmbGrupos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPCampoFecha;
    private javax.swing.JPanel jPCampoNombre;
    private javax.swing.JPanel jPFecha;
    private javax.swing.JPanel jPNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelBackGround;
    private javax.swing.JPanel jPanelBanner;
    private javax.swing.JPanel jPanelExit2;
    private javax.swing.JPanel jPanelSide;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAcTaller;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblExit2;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblHandle;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JPanel panelAgregar;
    private javax.swing.JPanel panelCancelar;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JPanel panelEliminar;
    // End of variables declaration//GEN-END:variables
}
