/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTAS;

import CONTROLADOR.Validaciones;
import CONTROLADOR.ctrlRegistroNuevoProfe;
import CONTROLADOR.ctrlRegistroReclusos;
import MODELO.Recluso;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelo Meza
 */
public class frmReclusosAlcaide extends javax.swing.JFrame {

    private ctrlRegistroReclusos controlador;
    private ctrlRegistroNuevoProfe ctrl;
    private DefaultTableModel modeloTabla;
    private Validaciones valido;

    /**
     * Creates new form frmAlcaide
     */
    public frmReclusosAlcaide() {
        initComponents();
        valido = new Validaciones();
        lblHandle.setText("admin");
        controlador = new ctrlRegistroReclusos();
        controlador.cargarDatosRecluso((DefaultTableModel) JTableReclusosExistentes.getModel());
        JTableReclusosExistentes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ctrl = new ctrlRegistroNuevoProfe();// Inicializar la instancia de la clase controladora
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackGround = new javax.swing.JPanel();
        jPanelSide = new javax.swing.JPanel();
        btnActividades = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnTalleres = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnProfesores = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnReclusos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblHandle = new javax.swing.JLabel();
        LlbIconUser = new javax.swing.JLabel();
        BtnOpcion5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanelBanner = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelExit2 = new javax.swing.JPanel();
        lblExit2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        JpaneREgisterReclusos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombresReo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtApellidosReo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCedulaReo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtAniosCondena = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDelitoReo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txtUsuarioReo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCorreoReo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl_idRecluso = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jDateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        txtPasswordReo = new javax.swing.JPasswordField();
        txtPasswConfirmReo = new javax.swing.JPasswordField();
        btnRegistrarReclusoNuevo = new javax.swing.JButton();
        btnEditarReo = new javax.swing.JButton();
        btnEliminarReo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableReclusosExistentes = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanelBackGround.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSide.setBackground(new java.awt.Color(54, 33, 89));
        jPanelSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActividades.setBackground(new java.awt.Color(64, 43, 100));
        btnActividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActividadesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActividadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActividadesMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("ACTIVIDADES");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/list.png"))); // NOI18N

        javax.swing.GroupLayout btnActividadesLayout = new javax.swing.GroupLayout(btnActividades);
        btnActividades.setLayout(btnActividadesLayout);
        btnActividadesLayout.setHorizontalGroup(
            btnActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActividadesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel9))
        );
        btnActividadesLayout.setVerticalGroup(
            btnActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActividadesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnActividadesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9))
        );

        jPanelSide.add(btnActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 290, 50));

        btnTalleres.setBackground(new java.awt.Color(64, 43, 100));
        btnTalleres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTalleres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTalleresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTalleresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTalleresMouseExited(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("TALLERES");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/group.png"))); // NOI18N

        javax.swing.GroupLayout btnTalleresLayout = new javax.swing.GroupLayout(btnTalleres);
        btnTalleres.setLayout(btnTalleresLayout);
        btnTalleresLayout.setHorizontalGroup(
            btnTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTalleresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4))
        );
        btnTalleresLayout.setVerticalGroup(
            btnTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTalleresLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnTalleresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4))
        );

        jPanelSide.add(btnTalleres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, 50));

        btnProfesores.setBackground(new java.awt.Color(64, 43, 100));
        btnProfesores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfesoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfesoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProfesoresMouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/teacher.png.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("PROFESORES");

        javax.swing.GroupLayout btnProfesoresLayout = new javax.swing.GroupLayout(btnProfesores);
        btnProfesores.setLayout(btnProfesoresLayout);
        btnProfesoresLayout.setHorizontalGroup(
            btnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProfesoresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel6))
        );
        btnProfesoresLayout.setVerticalGroup(
            btnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProfesoresLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnProfesoresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6))
        );

        jPanelSide.add(btnProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 290, 50));

        btnReclusos.setBackground(new java.awt.Color(85, 65, 118));
        btnReclusos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReclusos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReclusosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReclusosMouseExited(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/prison.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("RECLUSOS");

        javax.swing.GroupLayout btnReclusosLayout = new javax.swing.GroupLayout(btnReclusos);
        btnReclusos.setLayout(btnReclusosLayout);
        btnReclusosLayout.setHorizontalGroup(
            btnReclusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReclusosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel8))
        );
        btnReclusosLayout.setVerticalGroup(
            btnReclusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReclusosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnReclusosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8))
        );

        jPanelSide.add(btnReclusos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 290, 50));

        lblHandle.setBackground(new java.awt.Color(204, 204, 204));
        lblHandle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHandle.setForeground(new java.awt.Color(204, 204, 204));
        lblHandle.setText("USER");
        jPanelSide.add(lblHandle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        LlbIconUser.setForeground(new java.awt.Color(153, 153, 153));
        LlbIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/UserIconBanner.png"))); // NOI18N
        jPanelSide.add(LlbIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 40));

        BtnOpcion5.setBackground(new java.awt.Color(85, 55, 100));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/arrow.png"))); // NOI18N

        lblLogout.setBackground(new java.awt.Color(204, 204, 204));
        lblLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(204, 204, 204));
        lblLogout.setText("Log Out");
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BtnOpcion5Layout = new javax.swing.GroupLayout(BtnOpcion5);
        BtnOpcion5.setLayout(BtnOpcion5Layout);
        BtnOpcion5Layout.setHorizontalGroup(
            BtnOpcion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnOpcion5Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogout)
                .addGap(12, 12, 12))
        );
        BtnOpcion5Layout.setVerticalGroup(
            BtnOpcion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnOpcion5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogout)
                .addGap(14, 14, 14))
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelSide.add(BtnOpcion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 290, 50));

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 230, 20));

        jTextField1.setBackground(new java.awt.Color(54, 33, 89));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("ADMINISTRADOR");
        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField1.setFocusable(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 180, 40));

        jLabel1.setBackground(new java.awt.Color(54, 33, 89));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ROL:");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jPanelSide.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 220, 40));

        jPanelBackGround.add(jPanelSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, -1));

        jPanelBanner.setBackground(new java.awt.Color(122, 72, 221));
        jPanelBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("SISTEMA CARCELARIO - Reclusos");
        jPanelBanner.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 64, -1, -1));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("ALCAIDE");
        jPanelBanner.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 24, -1, -1));

        jPanelExit2.setBackground(new java.awt.Color(122, 72, 221));

        lblExit2.setBackground(new java.awt.Color(33, 45, 62));
        lblExit2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblExit2.setForeground(new java.awt.Color(255, 255, 255));
        lblExit2.setText("X");
        lblExit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExit2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelExit2Layout = new javax.swing.GroupLayout(jPanelExit2);
        jPanelExit2.setLayout(jPanelExit2Layout);
        jPanelExit2Layout.setHorizontalGroup(
            jPanelExit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExit2Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(lblExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelExit2Layout.setVerticalGroup(
            jPanelExit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanelBanner.add(jPanelExit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/prison.png"))); // NOI18N
        jPanelBanner.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jPanelBackGround.add(jPanelBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, 1080, -1));

        JpaneREgisterReclusos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombres:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        txtNombresReo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresReoKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombresReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, -1));

        jLabel14.setText("Apellidos:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        txtApellidosReo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosReoKeyTyped(evt);
            }
        });
        jPanel2.add(txtApellidosReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 170, -1));

        jLabel15.setText("Cédula:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        txtCedulaReo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaReoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCedulaReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 170, -1));

        jLabel16.setText("Tiempo Condena (Meses):");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        txtAniosCondena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAniosCondenaKeyTyped(evt);
            }
        });
        jPanel2.add(txtAniosCondena, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 50, -1));

        jLabel17.setText("Delito:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, 20));

        txtDelitoReo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDelitoReoKeyTyped(evt);
            }
        });
        jPanel2.add(txtDelitoReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 170, -1));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 255));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 580, 10));

        jLabel19.setText("Usuario:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        txtUsuarioReo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioReoKeyTyped(evt);
            }
        });
        jPanel2.add(txtUsuarioReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 170, -1));

        jLabel20.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel20.setText("CREDENCIALES");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel21.setText("Correo Electronico:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));
        jPanel2.add(txtCorreoReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 170, -1));

        jLabel22.setText("Contraseña:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        jLabel23.setText("Confirme su contraseña:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jLabel24.setText("ID:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_idRecluso.setText("#");
        jPanel2.add(lbl_idRecluso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, -1));

        jLabel26.setText("Fecha Nacimiento:");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jDateFechaNacimiento.setDateFormatString("yyyy/MM/dd");
        jDateFechaNacimiento.setFocusable(false);
        jDateFechaNacimiento.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateFechaNacimientoPropertyChange(evt);
            }
        });
        jPanel2.add(jDateFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 140, -1));
        jPanel2.add(txtPasswordReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 170, -1));
        jPanel2.add(txtPasswConfirmReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 170, -1));

        JpaneREgisterReclusos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 650, 350));

        btnRegistrarReclusoNuevo.setBackground(new java.awt.Color(153, 255, 102));
        btnRegistrarReclusoNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarReclusoNuevo.setText("REGISTRAR");
        btnRegistrarReclusoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarReclusoNuevoActionPerformed(evt);
            }
        });
        JpaneREgisterReclusos.add(btnRegistrarReclusoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 115, 45));

        btnEditarReo.setText("MODIFICAR");
        btnEditarReo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarReoActionPerformed(evt);
            }
        });
        JpaneREgisterReclusos.add(btnEditarReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 115, 45));

        btnEliminarReo.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarReo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarReo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarReo.setText("ELIMINAR");
        btnEliminarReo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarReoActionPerformed(evt);
            }
        });
        JpaneREgisterReclusos.add(btnEliminarReo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 115, 45));

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        JpaneREgisterReclusos.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 115, 33));

        JTableReclusosExistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_RECLCUSO", "NOMBRES", "APELLIDOS", "CEDULA", "CORREO", "DELITO", "TIEMPO_CONDENA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableReclusosExistentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableReclusosExistentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableReclusosExistentes);

        JpaneREgisterReclusos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 960, 110));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/editing.png"))); // NOI18N
        JpaneREgisterReclusos.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 43, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/cancel.png"))); // NOI18N
        JpaneREgisterReclusos.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 43, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/bin.png"))); // NOI18N
        JpaneREgisterReclusos.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 43, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/diskette.png"))); // NOI18N
        JpaneREgisterReclusos.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 43, -1));

        jPanelBackGround.add(JpaneREgisterReclusos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 1000, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExit2MouseClicked

    private void lblExit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseEntered
        jPanelExit2.setBackground(Color.red);
        lblExit2.setBackground(Color.white);
    }//GEN-LAST:event_lblExit2MouseEntered

    private void lblExit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseExited
        jPanelExit2.setBackground(new Color(122, 72, 221));
    }//GEN-LAST:event_lblExit2MouseExited

    private void btnActividadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActividadesMouseExited
        resetColor(btnTalleres);
        resetColor(btnActividades);
        resetColor(btnProfesores);
        setColor(btnReclusos);

    }//GEN-LAST:event_btnActividadesMouseExited

    private void btnTalleresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTalleresMouseExited
        resetColor(btnTalleres);
        resetColor(btnActividades);
        resetColor(btnProfesores);
        setColor(btnReclusos);
    }//GEN-LAST:event_btnTalleresMouseExited

    private void btnActividadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActividadesMouseEntered
        setColor(btnActividades);
        resetColor(btnTalleres);
        resetColor(btnProfesores);
        resetColor(btnReclusos);
    }//GEN-LAST:event_btnActividadesMouseEntered

    private void btnTalleresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTalleresMouseEntered
        setColor(btnTalleres);
        resetColor(btnActividades);
        resetColor(btnProfesores);
        resetColor(btnReclusos);
    }//GEN-LAST:event_btnTalleresMouseEntered

    private void btnProfesoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesoresMouseEntered
        setColor(btnProfesores);
        resetColor(btnTalleres);
        resetColor(btnActividades);
        resetColor(btnReclusos);
    }//GEN-LAST:event_btnProfesoresMouseEntered

    private void btnReclusosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReclusosMouseEntered
        setColor(btnReclusos);
        resetColor(btnTalleres);
        resetColor(btnProfesores);
        resetColor(btnActividades);
    }//GEN-LAST:event_btnReclusosMouseEntered

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // Mostrar mensaje de confirmación para cerrar sesión
        int opcion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas cerrar sesión?", "Cerrar sesión", JOptionPane.YES_NO_OPTION);

        // Verificar la opción seleccionada por el usuario
        if (opcion == JOptionPane.YES_OPTION) {
            // Mostrar mensaje de sesión cerrada con éxito
            JOptionPane.showMessageDialog(null, "Sesión cerrada con éxito", "Sesión cerrada", JOptionPane.INFORMATION_MESSAGE);

            // Cerrar el formulario actual
            this.dispose();

            // Cargar el formulario de login
            Login loginForm = new Login();
            loginForm.setVisible(true);
        }

    }//GEN-LAST:event_lblLogoutMouseClicked

    private void btnActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActividadesMouseClicked
        frmAlcaide Alcaide = new frmAlcaide();
        this.dispose();
        Alcaide.setVisible(true);
    }//GEN-LAST:event_btnActividadesMouseClicked

    private void btnProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesoresMouseClicked
        frmProfesoresAlcaide ProfesoresA = new frmProfesoresAlcaide();
        this.dispose();
        ProfesoresA.setVisible(true);

    }//GEN-LAST:event_btnProfesoresMouseClicked

    private void btnTalleresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTalleresMouseClicked
        frmTalleresAlcaide TalleresA = new frmTalleresAlcaide();
        this.dispose();
        TalleresA.setVisible(true);
    }//GEN-LAST:event_btnTalleresMouseClicked

    private void btnReclusosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReclusosMouseExited
        resetColor(btnTalleres);
        resetColor(btnActividades);
        resetColor(btnProfesores);
        setColor(btnReclusos);
    }//GEN-LAST:event_btnReclusosMouseExited

    private void btnProfesoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesoresMouseExited
        resetColor(btnTalleres);
        resetColor(btnActividades);
        resetColor(btnProfesores);
        setColor(btnReclusos);
    }//GEN-LAST:event_btnProfesoresMouseExited

    private void txtNombresReoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresReoKeyTyped
        valido.validarSoloLetras(evt);
    }//GEN-LAST:event_txtNombresReoKeyTyped

    private void txtApellidosReoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosReoKeyTyped
        valido.validarSoloLetras(evt);
    }//GEN-LAST:event_txtApellidosReoKeyTyped

    private void txtCedulaReoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaReoKeyTyped
        valido.validarCedula(evt, txtCedulaReo.getText());
    }//GEN-LAST:event_txtCedulaReoKeyTyped

    private void txtAniosCondenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAniosCondenaKeyTyped
        char c = evt.getKeyChar();
        String texto = txtAniosCondena.getText() + c;

        // Permitir solo dígitos y la tecla "Borrar"
        if (!Character.isDigit(c) && c != evt.VK_BACK_SPACE) {
            evt.consume();
            // Mostrar un JOptionPane informativo.
            JOptionPane.showMessageDialog(this,
                    "Solo se permiten números en los años de condena.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            // Verificar que no se ingresen más de dos dígitos
            if (texto.length() > 2) {
                evt.consume(); // Consumir la tecla si ya hay más de dos dígitos
            }
        }
    }//GEN-LAST:event_txtAniosCondenaKeyTyped

    private void txtDelitoReoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDelitoReoKeyTyped
        valido.validarSoloLetras(evt);
    }//GEN-LAST:event_txtDelitoReoKeyTyped

    private void txtUsuarioReoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioReoKeyTyped

        char c = evt.getKeyChar();
        // Permitir letras, números y la tecla "Borrar"
        if (!Character.isLetterOrDigit(c) && c != evt.VK_BACK_SPACE) {
            evt.consume();
            // Mostrar un JOptionPane informativo.
            JOptionPane.showMessageDialog(this,
                    "Solo se permiten letras y números en el usuario.\nRecuerde tambien que NO se admiten espacios",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtUsuarioReoKeyTyped

    private void btnRegistrarReclusoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarReclusoNuevoActionPerformed

        try {
            // Obtener los valores de los campos de texto
            String codigoRecluso = "#R0001";
            String cedula = txtCedulaReo.getText();
            String nombres = txtNombresReo.getText();
            String apellidos = txtApellidosReo.getText();
            String correo = valido.validarCorreoElectronico(txtCorreoReo.getText());
            String usuario = valido.validarNombreUsuario(txtUsuarioReo.getText());
            char[] password = txtPasswordReo.getPassword();
            char[] passwordConfirm = txtPasswConfirmReo.getPassword();
            String contraConfirm = new String(passwordConfirm);
            String contra = valido.validadContrasena(new String(password));
            int TimeCondena = Integer.parseInt(txtAniosCondena.getText());
            String delito = txtDelitoReo.getText();
            Date fechaNac = valido.ValidarFecha(jDateFechaNacimiento.getDate());

            //validar campos vacios
            if (txtCedulaReo.getText().isEmpty() || txtNombresReo.getText().isEmpty() || txtApellidosReo.getText().isEmpty()
                    || txtCorreoReo.getText().isEmpty() || txtAniosCondena.getText().isEmpty()
                    || txtUsuarioReo.getText().isEmpty() || password.length == 0 || passwordConfirm.length == 0 || txtDelitoReo.getText().isEmpty() || fechaNac == null) {
                JOptionPane.showMessageDialog(this,
                        "Existen campos vacios o datos invalidos, por favor verifique que los datos sean correctos.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                if (!contra.equals(contraConfirm)) {
                    JOptionPane.showMessageDialog(this,
                            "La contraseña no coincide con la confirmacion, por favor verifique sean iguales",
                            "Advertencia",
                            JOptionPane.WARNING_MESSAGE);
                    // Detener el evento
                    return;
                }else {
                    // Crear la instancia de Recluso
                    Recluso recluso = new Recluso(codigoRecluso, TimeCondena, delito, cedula, nombres, apellidos, usuario, contra, correo, fechaNac);
                    codigoRecluso = recluso.GenerarIdRecluso(cedula);
                    recluso.setCodigoRecluso(codigoRecluso);//asignar el id generado
                    // Crear el mensaje de confirmación
                    String mensaje = "¿Deseas Registar al recluso: " + recluso.getNombres() + " " + recluso.getApellidos() + "?";
                    int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Confirmar Resgistro", JOptionPane.YES_NO_OPTION);
                    // Verificar la opción seleccionada
                    if (opcion == JOptionPane.YES_OPTION) {
                        // Guardar los datos en la base de datos
                        controlador.RegistrarNuevoRecluso(recluso);
                        limpiarInputs();
                    } else {
                        // Detener el evento
                        return;
                    }
                }
                // Mostrar mensaje al usuario
                JOptionPane.showMessageDialog(this, "Los datos se han añadido correctamente.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos: " + e.getMessage());
        }
        // Actualizar la tabla de profesores (si es necesario)
        controlador.cargarDatosRecluso((DefaultTableModel) JTableReclusosExistentes.getModel());
    }//GEN-LAST:event_btnRegistrarReclusoNuevoActionPerformed

    private void btnEditarReoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarReoActionPerformed
        // Obtener los datos del profesor a editar
        String codigoRecluso = lbl_idRecluso.getText();
        if (!controlador.existeRecluso(codigoRecluso)) {
            JOptionPane.showMessageDialog(this,
                    "El recluso con el ID especificado no existe\n"
                    + "VERIFIQUE: que haya seleccionado a un Recluso/a .",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        String cedula = txtCedulaReo.getText();
        String nombres = txtNombresReo.getText();
        String apellidos = txtApellidosReo.getText();
        String correo = valido.validarCorreoElectronico(txtCorreoReo.getText());
        String usuario = valido.validarNombreUsuario(txtUsuarioReo.getText());
        char[] password = txtPasswordReo.getPassword();
        String Nuevacontra = new String(password);
        char[] passwordConf = txtPasswConfirmReo.getPassword();
        String NuevaContraConf = new String(passwordConf);
        int TimeCondena = Integer.parseInt(txtAniosCondena.getText());
        String delito = txtDelitoReo.getText();
        Date fechaNac = valido.ValidarFecha(jDateFechaNacimiento.getDate());

        if (cedula.isEmpty() || nombres.isEmpty() || apellidos.isEmpty() || correo.isEmpty() || txtAniosCondena.getText().isEmpty() || NuevaContraConf.isEmpty()
                || usuario.isEmpty() || NuevaContraConf.isEmpty() || delito.isEmpty() || fechaNac == null) {
            JOptionPane.showMessageDialog(this,
                    "Existen campos vacios o datos invalidos, por favor verifique que los datos sean correctos.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            // Crear la instancia de Recluso
            Recluso recluso = new Recluso(codigoRecluso, TimeCondena, delito, cedula, nombres, apellidos, usuario, Nuevacontra, correo, fechaNac);
            // Crear el mensaje de confirmación
            String mensaje = "¿Deseas Modificar al recluso: " + recluso.getNombres() + " " + recluso.getApellidos() + " ?";
            int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Confirmar Resgistro", JOptionPane.YES_NO_OPTION);
            // Verificar la opción seleccionada
            if (opcion == JOptionPane.YES_OPTION) {
                // Guardar los datos en la base de datos
                controlador.EditarRecluso(recluso);
                limpiarInputs();
            } else {
                // Detener el evento
                return;
            }
        }
        // Actualizar la tabla de profesores con los datos actualizados
        DefaultTableModel modeloTabla = (DefaultTableModel) JTableReclusosExistentes.getModel();
        modeloTabla.setRowCount(0); // Limpiar los datos existentes en la tabla
        controlador.cargarDatosRecluso(modeloTabla);

        // Mostrar un mensaje de éxito
        JOptionPane.showMessageDialog(this, "Recluso editado correctamente", "Edición exitosa", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEditarReoActionPerformed

    private void btnEliminarReoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarReoActionPerformed
        // Obtener el ID del profesor seleccionado
        String idRecluso = lbl_idRecluso.getText();
        if (!controlador.existeRecluso(idRecluso)) {
            JOptionPane.showMessageDialog(this,
                    "El recluso con el ID especificado no existe\n"
                    + "VERIFIQUE: que haya seleccionado a un Recluso/a .",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        String nombreReo = txtNombresReo.getText() + " " + txtApellidosReo.getText();
        int asignaciones = controlador.consultarAsignacionesRecluso(idRecluso);

        //Verificar si tiene asiganciones hechas
        if (asignaciones >= 1) {
            JOptionPane.showMessageDialog(this,
                    " " + nombreReo + "tiene " + asignaciones + " Asigancion/es"
                    + "\nSi elimina este Recluso/a tambien se"
                    + "\neliminaran sus asiganciones",
                    "Advertencia Eliminacion",
                    JOptionPane.WARNING_MESSAGE);
        }
        // Crear el mensaje de confirmación
        String mensaje = "¿Deseas Eliminar al recluso: " + nombreReo + " ?";
        int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Confirmar Resgistro", JOptionPane.YES_NO_OPTION);
        // Verificar la opción seleccionada
        if (opcion == JOptionPane.YES_OPTION) {
            // Llamar al método eliminarProfesor del controlador
            controlador.eliminarRecluso(idRecluso);
        } else {
            // Detener el evento
            return;
        }
        limpiarInputs();
        // Actualizar la tabla de profesores (si es necesario)
        controlador.cargarDatosRecluso((DefaultTableModel) JTableReclusosExistentes.getModel());
    }//GEN-LAST:event_btnEliminarReoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarInputs();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void JTableReclusosExistentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableReclusosExistentesMouseClicked
        int filaSeleccionada = JTableReclusosExistentes.getSelectedRow();
        List<Recluso> recluso = controlador.cargarDatosRecluso((DefaultTableModel) JTableReclusosExistentes.getModel());
        // Obtener el profesor seleccionado de la lista
        Recluso reo = recluso.get(filaSeleccionada);

        // Obtener los datos del profesor
        String idRecluso = reo.getCodigoRecluso();
        String cedula = reo.getCedula();
        String nombres = reo.getNombres();
        String apellidos = reo.getApellidos();
        int condena = reo.getTiempo_condena();
        String delito = reo.getDelito();
        String correo = reo.getCorreo();
        String usuario = reo.getUser();
        String contrasena = reo.getPassword();
        Date fechaNac = reo.getFechaNacimiento();
        // Establecer los datos en los campos de texto
        lbl_idRecluso.setText(idRecluso);
        txtNombresReo.setText(nombres);
        txtApellidosReo.setText(apellidos);
        txtCedulaReo.setText(cedula);
        txtCedulaReo.setEditable(false);
        txtCorreoReo.setText(correo);
        txtAniosCondena.setText("" + condena);
        txtDelitoReo.setText(delito);
        txtUsuarioReo.setText(usuario);
        txtPasswordReo.setText(contrasena);
        txtPasswConfirmReo.setText(contrasena);
        jDateFechaNacimiento.setDate(fechaNac);
        // Restaurar la selección después de la actualización
        if (filaSeleccionada != -1) {
            JTableReclusosExistentes.getSelectionModel().setSelectionInterval(filaSeleccionada, filaSeleccionada);
        }
    }//GEN-LAST:event_JTableReclusosExistentesMouseClicked

    private void jDateFechaNacimientoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateFechaNacimientoPropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName())) {
            // Obtener la fecha seleccionada en jDateFechaNacimiento
            Date fechaNacimiento = jDateFechaNacimiento.getDate();

            // Verificar que la fecha seleccionada no sea nula
            if (fechaNacimiento != null) {
                // Crear un calendario con la fecha actual
                Calendar calFechaActual = Calendar.getInstance();

                // Crear un calendario con la fecha de nacimiento seleccionada
                Calendar calFechaNacimiento = Calendar.getInstance();
                calFechaNacimiento.setTime(fechaNacimiento);

                // Calcular la fecha mínima permitida (18 años antes de la fecha actual)
                calFechaActual.add(Calendar.YEAR, -18);

                // Verificar si la fecha de nacimiento es menor a 18 años
                if (calFechaNacimiento.after(calFechaActual)) {
                    // La fecha de nacimiento no cumple con los requisitos, mostrar un mensaje de advertencia
                    JOptionPane.showMessageDialog(null,
                            "ERROR: La fecha de nacimiento debe ser superior a 18 años.",
                            "Advertencia",
                            JOptionPane.WARNING_MESSAGE);
                    jDateFechaNacimiento.setDate(null);
                }
            }
        }

    }//GEN-LAST:event_jDateFechaNacimientoPropertyChange
    void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(64, 43, 100));
    }

    private void limpiarInputs() {
        lbl_idRecluso.setText("");
        txtNombresReo.setText("");
        txtApellidosReo.setText("");
        txtCedulaReo.setText("");
        txtCedulaReo.setEditable(true);
        txtAniosCondena.setText("");
        txtDelitoReo.setText("");
        txtUsuarioReo.setText("");
        txtCorreoReo.setText("");
        txtPasswordReo.setText("");
        txtPasswConfirmReo.setText("");
        jDateFechaNacimiento.setDate(null);
        JTableReclusosExistentes.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReclusosAlcaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReclusosAlcaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReclusosAlcaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReclusosAlcaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReclusosAlcaide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnOpcion5;
    private javax.swing.JTable JTableReclusosExistentes;
    private javax.swing.JPanel JpaneREgisterReclusos;
    private javax.swing.JLabel LlbIconUser;
    private javax.swing.JPanel btnActividades;
    private javax.swing.JButton btnEditarReo;
    private javax.swing.JButton btnEliminarReo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel btnProfesores;
    private javax.swing.JPanel btnReclusos;
    private javax.swing.JButton btnRegistrarReclusoNuevo;
    private javax.swing.JPanel btnTalleres;
    private com.toedter.calendar.JDateChooser jDateFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBackGround;
    private javax.swing.JPanel jPanelBanner;
    private javax.swing.JPanel jPanelExit2;
    private javax.swing.JPanel jPanelSide;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblExit2;
    private javax.swing.JLabel lblHandle;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lbl_idRecluso;
    private javax.swing.JTextField txtAniosCondena;
    private javax.swing.JTextField txtApellidosReo;
    private javax.swing.JTextField txtCedulaReo;
    private javax.swing.JTextField txtCorreoReo;
    private javax.swing.JTextField txtDelitoReo;
    private javax.swing.JTextField txtNombresReo;
    private javax.swing.JPasswordField txtPasswConfirmReo;
    private javax.swing.JPasswordField txtPasswordReo;
    private javax.swing.JTextField txtUsuarioReo;
    // End of variables declaration//GEN-END:variables

}
