/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTAS;

import CONTROLADOR.ctrlRegistroNuevoProfe;
import CONTROLADOR.ctrlRegistroReclusos;
import MODELO.AsignacionRecluso;
import MODELO.Recluso;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelo Meza
 */
public class frmReclusosAlcaide extends javax.swing.JFrame {

    private ctrlRegistroReclusos controlador;
    private ctrlRegistroNuevoProfe ctrl;
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form frmAlcaide
     */
    public frmReclusosAlcaide() {
        initComponents();
        controlador = new ctrlRegistroReclusos();
        ctrl = new ctrlRegistroNuevoProfe();// Inicializar la instancia de la clase controladora
        controlador.cargarReclusosComboBox(CmbReclusosExistentes);
        controlador.cargarDatosAsignacionesReos((DefaultTableModel) JTableAsigancionRecluso.getModel());
        JTableAsigancionRecluso.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //elementos que solo se visualiazn para Talleres
        lblGrupo.setVisible(false);
        CmbGrupos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackGround = new javax.swing.JPanel();
        jPanelSide = new javax.swing.JPanel();
        btnActividades = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnTalleres = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnProfesores = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnReclusos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LlbIconUser = new javax.swing.JLabel();
        BtnOpcion5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanelBanner = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelExit2 = new javax.swing.JPanel();
        lblExit2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableAsigancionRecluso = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        panelAgregar = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        panelCancelar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        panelEditar = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        panelEliminar = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        lblActTaller = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPNombre = new javax.swing.JPanel();
        jPCampoNombre = new javax.swing.JPanel();
        jPCampoFecha = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        CmbActividadTaller = new javax.swing.JComboBox<>();
        CmbGrupos = new javax.swing.JComboBox<>();
        CmbReclusosExistentes = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        lbl_IDrecluso = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CmbAsignacionRecluso = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnAdminReclusos = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanelBackGround.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSide.setBackground(new java.awt.Color(54, 33, 89));
        jPanelSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActividades.setBackground(new java.awt.Color(64, 43, 100));
        btnActividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActividadesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActividadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActividadesMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("ACTIVIDADES");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/list.png"))); // NOI18N

        javax.swing.GroupLayout btnActividadesLayout = new javax.swing.GroupLayout(btnActividades);
        btnActividades.setLayout(btnActividadesLayout);
        btnActividadesLayout.setHorizontalGroup(
            btnActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActividadesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel9))
        );
        btnActividadesLayout.setVerticalGroup(
            btnActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActividadesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnActividadesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9))
        );

        jPanelSide.add(btnActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 290, 50));

        btnTalleres.setBackground(new java.awt.Color(64, 43, 100));
        btnTalleres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTalleres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTalleresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTalleresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTalleresMouseExited(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("TALLERES");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/group.png"))); // NOI18N

        javax.swing.GroupLayout btnTalleresLayout = new javax.swing.GroupLayout(btnTalleres);
        btnTalleres.setLayout(btnTalleresLayout);
        btnTalleresLayout.setHorizontalGroup(
            btnTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTalleresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4))
        );
        btnTalleresLayout.setVerticalGroup(
            btnTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTalleresLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnTalleresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4))
        );

        jPanelSide.add(btnTalleres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, 50));

        btnProfesores.setBackground(new java.awt.Color(64, 43, 100));
        btnProfesores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfesoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfesoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProfesoresMouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/teacher.png.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("PROFESORES");

        javax.swing.GroupLayout btnProfesoresLayout = new javax.swing.GroupLayout(btnProfesores);
        btnProfesores.setLayout(btnProfesoresLayout);
        btnProfesoresLayout.setHorizontalGroup(
            btnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProfesoresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel6))
        );
        btnProfesoresLayout.setVerticalGroup(
            btnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProfesoresLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnProfesoresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6))
        );

        jPanelSide.add(btnProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 290, 50));

        btnReclusos.setBackground(new java.awt.Color(85, 65, 118));
        btnReclusos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReclusos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReclusosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReclusosMouseExited(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/prison.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("RECLUSOS");

        javax.swing.GroupLayout btnReclusosLayout = new javax.swing.GroupLayout(btnReclusos);
        btnReclusos.setLayout(btnReclusosLayout);
        btnReclusosLayout.setHorizontalGroup(
            btnReclusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReclusosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel8))
        );
        btnReclusosLayout.setVerticalGroup(
            btnReclusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReclusosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnReclusosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8))
        );

        jPanelSide.add(btnReclusos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 290, 50));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("USER");
        jPanelSide.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        LlbIconUser.setForeground(new java.awt.Color(153, 153, 153));
        LlbIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/UserIconBanner.png"))); // NOI18N
        jPanelSide.add(LlbIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 40));

        BtnOpcion5.setBackground(new java.awt.Color(85, 55, 100));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/arrow.png"))); // NOI18N

        lblLogout.setBackground(new java.awt.Color(204, 204, 204));
        lblLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(204, 204, 204));
        lblLogout.setText("Log Out");
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BtnOpcion5Layout = new javax.swing.GroupLayout(BtnOpcion5);
        BtnOpcion5.setLayout(BtnOpcion5Layout);
        BtnOpcion5Layout.setHorizontalGroup(
            BtnOpcion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnOpcion5Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogout)
                .addGap(12, 12, 12))
        );
        BtnOpcion5Layout.setVerticalGroup(
            BtnOpcion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnOpcion5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogout)
                .addGap(14, 14, 14))
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelSide.add(BtnOpcion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 290, 50));

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 230, 20));

        jTextField1.setBackground(new java.awt.Color(54, 33, 89));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("ADMINISTRADOR");
        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField1.setFocusable(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 180, 40));

        jLabel1.setBackground(new java.awt.Color(54, 33, 89));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ROL:");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jPanelSide.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 220, 40));

        jPanelBackGround.add(jPanelSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, -1));

        jPanelBanner.setBackground(new java.awt.Color(122, 72, 221));
        jPanelBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("SISTEMA CARCELARIO - Reclusos");
        jPanelBanner.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 64, -1, -1));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("ALCAIDE");
        jPanelBanner.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 24, -1, -1));

        jPanelExit2.setBackground(new java.awt.Color(122, 72, 221));

        lblExit2.setBackground(new java.awt.Color(33, 45, 62));
        lblExit2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblExit2.setForeground(new java.awt.Color(255, 255, 255));
        lblExit2.setText("X");
        lblExit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExit2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelExit2Layout = new javax.swing.GroupLayout(jPanelExit2);
        jPanelExit2.setLayout(jPanelExit2Layout);
        jPanelExit2Layout.setHorizontalGroup(
            jPanelExit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExit2Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(lblExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelExit2Layout.setVerticalGroup(
            jPanelExit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanelBanner.add(jPanelExit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/prison.png"))); // NOI18N
        jPanelBanner.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 0, 102));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/sync.png"))); // NOI18N
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        jPanelBanner.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 30, -1));

        jPanelBackGround.add(jPanelBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, 1080, -1));

        JTableAsigancionRecluso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JTableAsigancionRecluso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Asignacion", "Nombre Recluso", "ID_RECLUSO", "Tipo_Asignacion", "Nombre Actividad/Taller", "ID_ACT/TALLER", "Grupo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableAsigancionRecluso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JTableAsigancionRecluso.setGridColor(new java.awt.Color(255, 255, 255));
        JTableAsigancionRecluso.setIntercellSpacing(new java.awt.Dimension(5, 5));
        JTableAsigancionRecluso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableAsigancionReclusoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableAsigancionRecluso);
        if (JTableAsigancionRecluso.getColumnModel().getColumnCount() > 0) {
            JTableAsigancionRecluso.getColumnModel().getColumn(0).setResizable(false);
            JTableAsigancionRecluso.getColumnModel().getColumn(0).setPreferredWidth(10);
            JTableAsigancionRecluso.getColumnModel().getColumn(1).setResizable(false);
            JTableAsigancionRecluso.getColumnModel().getColumn(1).setPreferredWidth(10);
            JTableAsigancionRecluso.getColumnModel().getColumn(2).setResizable(false);
            JTableAsigancionRecluso.getColumnModel().getColumn(3).setResizable(false);
            JTableAsigancionRecluso.getColumnModel().getColumn(3).setPreferredWidth(10);
            JTableAsigancionRecluso.getColumnModel().getColumn(4).setResizable(false);
            JTableAsigancionRecluso.getColumnModel().getColumn(5).setResizable(false);
            JTableAsigancionRecluso.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanelBackGround.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 1080, 320));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("ID:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 22, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 10, 278));

        panelAgregar.setBackground(new java.awt.Color(204, 204, 204));
        panelAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelAgregar.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/diskette.png"))); // NOI18N
        panelAgregar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 43, -1));

        jPanel2.add(panelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 140, -1));

        panelCancelar.setBackground(new java.awt.Color(204, 204, 204));
        panelCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelCancelar.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/cancel.png"))); // NOI18N
        panelCancelar.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 43, -1));

        jPanel2.add(panelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 140, -1));

        panelEditar.setBackground(new java.awt.Color(204, 204, 204));
        panelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEditar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditar.setText("Modificar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panelEditar.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/editing.png"))); // NOI18N
        panelEditar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 43, -1));

        jPanel2.add(panelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 140, -1));

        panelEliminar.setBackground(new java.awt.Color(204, 204, 204));
        panelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelEliminar.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/bin.png"))); // NOI18N
        panelEliminar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 43, -1));

        jPanel2.add(panelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, 140, -1));

        lblActTaller.setText("Actividad o Taller:");
        jPanel2.add(lblActTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 110, -1));

        lblGrupo.setText("Grupo:");
        jPanel2.add(lblGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 40, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 21, -1, -1));

        jPNombre.setBackground(new java.awt.Color(204, 204, 204));
        jPNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 78, 210, -1));

        jPCampoNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPCampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 43, 180, -1));

        jPCampoFecha.setBackground(new java.awt.Color(204, 204, 204));
        jPCampoFecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPCampoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 116, -1, 38));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 184, 420, 17));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 620, 10));

        CmbActividadTaller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--" }));
        CmbActividadTaller.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbActividadTallerItemStateChanged(evt);
            }
        });
        jPanel2.add(CmbActividadTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 158, -1));

        jPanel2.add(CmbGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 133, -1));

        CmbReclusosExistentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecione--" }));
        CmbReclusosExistentes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbReclusosExistentesItemStateChanged(evt);
            }
        });
        jPanel2.add(CmbReclusosExistentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 118, 180, -1));

        jLabel17.setText("Asignacion:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        lbl_IDrecluso.setBackground(new java.awt.Color(255, 255, 255));
        lbl_IDrecluso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_IDrecluso.setText("#R001");
        jPanel2.add(lbl_IDrecluso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 70, -1));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Nombre de Recluso:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        CmbAsignacionRecluso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "Actividad", "Taller" }));
        CmbAsignacionRecluso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbAsignacionReclusoItemStateChanged(evt);
            }
        });
        CmbAsignacionRecluso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbAsignacionReclusoActionPerformed(evt);
            }
        });
        jPanel2.add(CmbAsignacionRecluso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 180, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        btnAdminReclusos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAdminReclusos.setText("Administrar \nReclusos");
        btnAdminReclusos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminReclusosActionPerformed(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagenes_Alcaide/AdminReo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdminReclusos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnAdminReclusos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, -1, -1));

        jLabel19.setText("Edad:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        lblEdad.setText("________");
        jPanel2.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        jPanelBackGround.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 1080, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 1367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExit2MouseClicked

    private void lblExit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseEntered
        jPanelExit2.setBackground(Color.red);
        lblExit2.setBackground(Color.white);
    }//GEN-LAST:event_lblExit2MouseEntered

    private void lblExit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseExited
        jPanelExit2.setBackground(new Color(122, 72, 221));
    }//GEN-LAST:event_lblExit2MouseExited

    private void btnActividadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActividadesMouseExited
        resetColor(btnActividades);
        setColor(btnTalleres);
        resetColor(btnProfesores);
        resetColor(btnReclusos);

    }//GEN-LAST:event_btnActividadesMouseExited

    private void btnTalleresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTalleresMouseExited
        setColor(btnActividades);
        setColor(btnTalleres);
        resetColor(btnProfesores);
        resetColor(btnReclusos);
    }//GEN-LAST:event_btnTalleresMouseExited

    private void btnProfesoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesoresMouseExited
        resetColor(btnActividades);
        setColor(btnTalleres);
        resetColor(btnProfesores);
        resetColor(btnReclusos);    }//GEN-LAST:event_btnProfesoresMouseExited

    private void btnReclusosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReclusosMouseExited
        resetColor(btnActividades);
        setColor(btnTalleres);
        resetColor(btnProfesores);
        resetColor(btnReclusos);    }//GEN-LAST:event_btnReclusosMouseExited

    private void btnActividadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActividadesMouseEntered
        setColor(btnActividades);
        resetColor(btnTalleres);
        resetColor(btnProfesores);
        resetColor(btnReclusos);
    }//GEN-LAST:event_btnActividadesMouseEntered

    private void btnTalleresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTalleresMouseEntered
        setColor(btnTalleres);
        resetColor(btnActividades);
        resetColor(btnProfesores);
        resetColor(btnReclusos);
    }//GEN-LAST:event_btnTalleresMouseEntered

    private void btnProfesoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesoresMouseEntered
        setColor(btnProfesores);
        resetColor(btnTalleres);
        resetColor(btnActividades);
        resetColor(btnReclusos);
    }//GEN-LAST:event_btnProfesoresMouseEntered

    private void btnReclusosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReclusosMouseEntered
        setColor(btnReclusos);
        resetColor(btnTalleres);
        resetColor(btnProfesores);
        resetColor(btnActividades);
    }//GEN-LAST:event_btnReclusosMouseEntered

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // Mostrar mensaje de confirmación para cerrar sesión
        int opcion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas cerrar sesión?", "Cerrar sesión", JOptionPane.YES_NO_OPTION);

        // Verificar la opción seleccionada por el usuario
        if (opcion == JOptionPane.YES_OPTION) {
            // Mostrar mensaje de sesión cerrada con éxito
            JOptionPane.showMessageDialog(null, "Sesión cerrada con éxito", "Sesión cerrada", JOptionPane.INFORMATION_MESSAGE);

            // Cerrar el formulario actual
            this.dispose();

            // Cargar el formulario de login
            Login loginForm = new Login();
            loginForm.setVisible(true);
        }

    }//GEN-LAST:event_lblLogoutMouseClicked

    private void btnActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActividadesMouseClicked
        frmAlcaide Alcaide = new frmAlcaide();
        this.dispose();
        Alcaide.setVisible(true);
    }//GEN-LAST:event_btnActividadesMouseClicked

    private void btnProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesoresMouseClicked
        frmProfesoresAlcaide ProfesoresA = new frmProfesoresAlcaide();
        this.dispose();
        ProfesoresA.setVisible(true);

    }//GEN-LAST:event_btnProfesoresMouseClicked

    private void btnTalleresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTalleresMouseClicked
        frmTalleresAlcaide TalleresA = new frmTalleresAlcaide();
        this.dispose();
        TalleresA.setVisible(true);
    }//GEN-LAST:event_btnTalleresMouseClicked

    private void CmbAsignacionReclusoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbAsignacionReclusoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbAsignacionReclusoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
         List<AsignacionRecluso> asignaciones = controlador.Lista_AsignacionesReos();
        if(asignaciones.isEmpty()){
                JOptionPane.showMessageDialog(this,
                        "No existen Asignaciones aun\n"
                                + "Cree primero un asignacion para poder editar.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
                return;
        }else if (lbl_IDrecluso.getText().isEmpty() || CmbReclusosExistentes.getSelectedIndex() == 0
                    || CmbActividadTaller.getSelectedIndex() == 0 || CmbAsignacionRecluso.getSelectedIndex() == 0
                    || lblEdad.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No ha selecionado una asignacion, por favor seleccione alguna de la tabla.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
        // Obtener los datos del asigancion a editar
        DefaultTableModel modeloTabla = (DefaultTableModel) JTableAsigancionRecluso.getModel();//modelo para obetner IDasignacion
        int filaSeleccionada = JTableAsigancionRecluso.getSelectedRow();
        String idAsignacion = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
        String idRecluso = lbl_IDrecluso.getText();
        String Nuevo_nombreRecluso = (String) CmbReclusosExistentes.getSelectedItem();
        String Nuevo_tipoAsignacion = (String) CmbAsignacionRecluso.getSelectedItem();
        String Nuevo_nombreActividadTaller = (String) CmbActividadTaller.getSelectedItem();
        String Nuevo_nombreGrupo = (String) CmbGrupos.getSelectedItem();
        String Nuevo_idActividadTaller = "";
        if (Nuevo_tipoAsignacion.equals("Actividad")) {
            Nuevo_idActividadTaller = ctrl.ObtenerActividad(Nuevo_nombreActividadTaller);
            Nuevo_nombreGrupo = " ";
        } else if (Nuevo_tipoAsignacion.equals("Taller")) {
            Nuevo_idActividadTaller = ctrl.ObtenerTaller(Nuevo_nombreActividadTaller);
        }
        AsignacionRecluso asignacion = new AsignacionRecluso(idAsignacion, idRecluso, Nuevo_nombreRecluso,
                Nuevo_tipoAsignacion, Nuevo_nombreActividadTaller, Nuevo_idActividadTaller, Nuevo_nombreGrupo);

        // Crear el mensaje de confirmación
        String mensaje = "¿Deseas Editar la asignación con ID: " + idAsignacion + "?";
        int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        // Verificar la opción seleccionada
        if (opcion == JOptionPane.YES_OPTION) {
            // Llamar al método eliminarAsignacion del controlador
            controlador.editarAsignacion(asignacion);
            limpiarInputs();
        } else {
            // Detener el evento
            return;
        }
        // Actualizar la tabla de Asignaciones con los datos actualizados
        modeloTabla.setRowCount(0); // Limpiar los datos existentes en la tabla
        controlador.cargarDatosAsignacionesReos(modeloTabla);

        // Mostrar un mensaje de éxito
        JOptionPane.showMessageDialog(this, "Asignacion editada correctamente", "Edición exitosa", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // cuando de click se limpian los input
        limpiarInputs();
        //actualizar tabla
        DefaultTableModel modeloTabla = (DefaultTableModel) JTableAsigancionRecluso.getModel();
        modeloTabla.setRowCount(0); // Limpiar los datos existentes en la tabla
        controlador.cargarDatosAsignacionesReos(modeloTabla);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            // Obtener los valores necesarios para la asignación desde los campos de la interfaz
            String idRecluso = lbl_IDrecluso.getText();
            String nombreRecluso = (String) CmbReclusosExistentes.getSelectedItem();
            String tipoAsignacion = (String) CmbAsignacionRecluso.getSelectedItem();
            String nombreActividadTaller = (String) CmbActividadTaller.getSelectedItem();
            String nombreGrupo = (String) CmbGrupos.getSelectedItem();
            String idActividadTaller = "";
            if (tipoAsignacion.equals("Actividad")) {
                idActividadTaller = ctrl.ObtenerActividad(nombreActividadTaller);
                nombreGrupo = " ";
            } else if (tipoAsignacion.equals("Taller")) {
                idActividadTaller = ctrl.ObtenerTaller(nombreActividadTaller);
            }
            if (lbl_IDrecluso.getText().isEmpty() || CmbReclusosExistentes.getSelectedIndex() == 0
                    || CmbActividadTaller.getSelectedIndex() == 0 || CmbAsignacionRecluso.getSelectedIndex() == 0
                    || lblEdad.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Existen campos vacios, por favor seleccione que los datos correctos.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                // Crear la instancia de Recluso
                AsignacionRecluso asigancion = new AsignacionRecluso("", idRecluso, nombreRecluso, tipoAsignacion,
                        nombreActividadTaller, idActividadTaller, nombreGrupo);

                // Crear el mensaje de confirmación
                String mensaje = "¿Deseas Registar al recluso: " + nombreRecluso + " en " + nombreActividadTaller + " ?";
                int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Confirmar Resgistro", JOptionPane.YES_NO_OPTION);
                // Verificar la opción seleccionada
                if (opcion == JOptionPane.YES_OPTION) {
                    // Llamar al método en tu controlador para agregar la asignación de recluso
                    controlador.agregarAsignacionRecluso(asigancion);
                    limpiarInputs();
                } else {
                    // Detener el evento
                    return;
                }

                // Mostrar mensaje al usuario
                JOptionPane.showMessageDialog(this, "Los datos se han añadido correctamente.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos: " + e.getMessage());
        }
        // Actualizar la tabla de profesores (si es necesario)
        controlador.cargarDatosAsignacionesReos((DefaultTableModel) JTableAsigancionRecluso.getModel());
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAdminReclusosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminReclusosActionPerformed
        frmCreateNewRecluso profe = new frmCreateNewRecluso();
        profe.setVisible(true);
    }//GEN-LAST:event_btnAdminReclusosActionPerformed

    private void CmbReclusosExistentesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbReclusosExistentesItemStateChanged
        String Cmbrecluso = (String) CmbReclusosExistentes.getSelectedItem();
        List<Recluso> reclusos = controlador.cargarDatosRecluso();
        String IDrecluso = "";
        int edad=0;
        for (Recluso reo : reclusos) {
            if ((reo.getNombres() + " " + reo.getApellidos()).equalsIgnoreCase(Cmbrecluso)) {
                IDrecluso = reo.getCodigoRecluso();
                edad=reo.CalcularEdad(reo.getFechaNacimiento());
            }
        }
        lbl_IDrecluso.setText(IDrecluso);
        if(edad==0){
            lblEdad.setText("");
        }else{
        lblEdad.setText(edad+" años");}
    }//GEN-LAST:event_CmbReclusosExistentesItemStateChanged

    private void CmbAsignacionReclusoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbAsignacionReclusoItemStateChanged
        //Obtener la opcion Selecionada: Actividad o Taller.
        String opcion = (String) CmbAsignacionRecluso.getSelectedItem();
        // Verificar la opción seleccionada
        if (opcion.equals("Actividad")) {
            CmbActividadTaller.removeAllItems();
            lblGrupo.setVisible(false);
            CmbGrupos.setVisible(false);
            ctrl.cargarActividadesComboBox(CmbActividadTaller);
        } else if (opcion.equals("Taller")) {
            CmbActividadTaller.removeAllItems();
            lblGrupo.setVisible(true);
            CmbGrupos.setVisible(true);
            ctrl.cargarTalleresComboBox(CmbActividadTaller);
        }


    }//GEN-LAST:event_CmbAsignacionReclusoItemStateChanged

    private void CmbActividadTallerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbActividadTallerItemStateChanged
        //Obtener la opcion Selecionada: Actividad o Taller.
        String opcion = (String) CmbAsignacionRecluso.getSelectedItem();
        // Verificar la opción seleccionada
        if (opcion.equals("Actividad")) {
            lblActTaller.setText("Actividad: ");
        }
        if (opcion.equals("Taller")) {
            lblActTaller.setText("Taller: :");
            CmbGrupos.removeAllItems();
            String NombreTaller = (String) CmbActividadTaller.getSelectedItem();
            String IdTaller = ctrl.ObtenerTaller(NombreTaller);
            ctrl.cargarGruposTalleres(IdTaller, CmbGrupos);
        }
    }//GEN-LAST:event_CmbActividadTallerItemStateChanged

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        // limpiar inputs
        limpiarInputs();
        // Actualizar la tabla de Asignaciones con los datos actualizados
        DefaultTableModel modeloTabla = (DefaultTableModel) JTableAsigancionRecluso.getModel();
        modeloTabla.setRowCount(0); // Limpiar los datos existentes en la tabla
        controlador.cargarDatosAsignacionesReos(modeloTabla);
        controlador.cargarReclusosComboBox(CmbReclusosExistentes);
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         List<AsignacionRecluso> asignaciones = controlador.Lista_AsignacionesReos();
        if(asignaciones.isEmpty()){
                JOptionPane.showMessageDialog(this,
                        "No existen Asignaciones aun\n"
                                + "Cree primero un asignacion para poder eliminar.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
                return;
        }else if (lbl_IDrecluso.getText().isEmpty() || CmbReclusosExistentes.getSelectedIndex() == 0
                    || CmbActividadTaller.getSelectedIndex() == 0 || CmbAsignacionRecluso.getSelectedIndex() == 0
                    || lblEdad.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No ha selecionado una asignacion, por favor seleccione alguna de la tabla.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
        // Obtener los datos del asigancion a Eliminar
        DefaultTableModel modeloTabla = (DefaultTableModel) JTableAsigancionRecluso.getModel();//modelo para obetner IDasignacion
        int filaSeleccionada = JTableAsigancionRecluso.getSelectedRow();
        String idAsignacion = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
        // Crear el mensaje de confirmación
        String mensaje = "¿Deseas eliminar la asignación con ID: " + idAsignacion + "?";
        int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        // Verificar la opción seleccionada
        if (opcion == JOptionPane.YES_OPTION) {
            // Llamar al método eliminarAsignacion del controlador
            controlador.eliminarAsignacion(idAsignacion);
            limpiarInputs();
        } else {
            // Detener el evento
            return;
        }

        // Actualizar la tabla de profesores (si es necesario)
        controlador.cargarDatosAsignacionesReos(modeloTabla);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void JTableAsigancionReclusoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableAsigancionReclusoMouseClicked
        int filaSeleccionada = JTableAsigancionRecluso.getSelectedRow();
        List<AsignacionRecluso> asignaciones = controlador.cargarDatosAsignacionesReos((DefaultTableModel) JTableAsigancionRecluso.getModel());
        // Obtener el recluso  seleccionado de la lista
        AsignacionRecluso asignacion = asignaciones.get(filaSeleccionada);
        CmbReclusosExistentes.removeAllItems();
        controlador.cargarReclusosComboBox(CmbReclusosExistentes);//cargarcombobox
        // Obtener los datos del recluso
        String idAsignacion = asignacion.getIdAsignacion();
        String idRecluso = asignacion.getIdRecluso();
        String NombreReo = asignacion.getNombreRecluso();
        String tipoAsignacion = asignacion.getTipoAsignacion();
        String Nombre_ActTaller = asignacion.getNombreActividadTaller();
        String NombreGrupo = asignacion.getNombreGrupo();
        String edad = "";

        //Para obtener la edad
        List<Recluso> reo = controlador.cargarDatosRecluso();
        for (Recluso recluso : reo) {
            if (recluso.getCodigoRecluso().equals(idRecluso)) {
                edad = recluso.CalcularEdad(recluso.getFechaNacimiento()) + " años";
            }

        }
        System.out.println("la edad del recluso es: " + edad);
        // Establecer los datos en los campos de texto
        lbl_IDrecluso.setText("" + idRecluso);
        lblEdad.setText(edad);
        CmbReclusosExistentes.setSelectedItem(NombreReo);
        CmbAsignacionRecluso.setSelectedItem(tipoAsignacion);
        CmbActividadTaller.setSelectedItem(Nombre_ActTaller);
        CmbGrupos.setSelectedItem(NombreGrupo);
        // Restaurar la selección después de la actualización
        if (filaSeleccionada != -1) {
            JTableAsigancionRecluso.getSelectionModel().setSelectionInterval(filaSeleccionada, filaSeleccionada);
        }
    }//GEN-LAST:event_JTableAsigancionReclusoMouseClicked
    void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(64, 43, 100));
    }

    private void limpiarInputs() {
        lbl_IDrecluso.setText("");
        lblEdad.setText("");
        CmbReclusosExistentes.setSelectedIndex(0);
        CmbAsignacionRecluso.setSelectedIndex(0);
        CmbActividadTaller.setSelectedIndex(0);
        if (CmbGrupos.isVisible()) {
            CmbGrupos.setSelectedIndex(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReclusosAlcaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReclusosAlcaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReclusosAlcaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReclusosAlcaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReclusosAlcaide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnOpcion5;
    private javax.swing.JComboBox<String> CmbActividadTaller;
    private javax.swing.JComboBox<String> CmbAsignacionRecluso;
    private javax.swing.JComboBox<String> CmbGrupos;
    private javax.swing.JComboBox<String> CmbReclusosExistentes;
    private javax.swing.JTable JTableAsigancionRecluso;
    private javax.swing.JLabel LlbIconUser;
    private javax.swing.JPanel btnActividades;
    private javax.swing.JLabel btnActualizar;
    private javax.swing.JButton btnAdminReclusos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel btnProfesores;
    private javax.swing.JPanel btnReclusos;
    private javax.swing.JPanel btnTalleres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPCampoFecha;
    private javax.swing.JPanel jPCampoNombre;
    private javax.swing.JPanel jPNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelBackGround;
    private javax.swing.JPanel jPanelBanner;
    private javax.swing.JPanel jPanelExit2;
    private javax.swing.JPanel jPanelSide;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblActTaller;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblExit2;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lbl_IDrecluso;
    private javax.swing.JPanel panelAgregar;
    private javax.swing.JPanel panelCancelar;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JPanel panelEliminar;
    // End of variables declaration//GEN-END:variables

}
